package xsdgen

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"go/token"
	"strconv"
)

var (
	ErrUnsupportedComplexGeneration = errors.New(
		"xsdgen: unsupported complex type generation",
	)
	ErrGoFieldNameCollision = errors.New(
		"xsdgen: Go field name collision",
	)
)

// GoFieldNameCollisionError reports fields in one generated structure that
// normalize to the same Go identifier.
type GoFieldNameCollisionError struct {
	Owner  string
	Name   string
	First  string
	Second string
}

func (e *GoFieldNameCollisionError) Error() string {
	return fmt.Sprintf(
		"%v %q in %s: %s and %s",
		ErrGoFieldNameCollision,
		e.Name,
		e.Owner,
		e.First,
		e.Second,
	)
}

func (e *GoFieldNameCollisionError) Unwrap() error {
	return ErrGoFieldNameCollision
}

// GenerateComplexTypes generates one formatted Go source file containing all
// named XSD complex types in index.
func GenerateComplexTypes(
	index *Index,
	packageName string,
) ([]byte, error) {
	return GenerateComplexTypesWithOptions(
		index,
		packageName,
		ComplexGenerationOptions{},
	)
}

// ComplexGenerationOptions controls complex-type representation choices.
//
// OrderedContentTypes identifies complex types whose entire element particle
// must be represented by one ordered Content slice. This is needed when the
// same element can occur at multiple positions and flattening the XSD particle
// into one field per element would lose order or values.
type ComplexGenerationOptions struct {
	OrderedContentTypes []QName
}

// GenerateComplexTypesWithOptions generates named XSD complex types using
// explicit representation options.
func GenerateComplexTypesWithOptions(
	index *Index,
	packageName string,
	options ComplexGenerationOptions,
) ([]byte, error) {
	if index == nil {
		return nil, ErrNilIndex
	}
	if !token.IsIdentifier(packageName) {
		return nil, fmt.Errorf(
			"%w %q",
			ErrInvalidPackageName,
			packageName,
		)
	}

	names, err := NewTypeNames(index)
	if err != nil {
		return nil, err
	}

	simplePlans, err := PlanSimpleTypes(index)
	if err != nil {
		return nil, err
	}

	complexPlans, err := PlanExpandedComplexTypes(index)
	if err != nil {
		return nil, err
	}
	orderedContentTypes, err := resolveOrderedContentTypes(
		index,
		options.OrderedContentTypes,
	)
	if err != nil {
		return nil, err
	}

	simpleRenderer := &simpleTypeRenderer{
		names:      names,
		plans:      make(map[*Declaration]*SimpleTypeDefinition, len(simplePlans)),
		kindStates: make(map[*Declaration]resolveState, len(simplePlans)),
		kinds:      make(map[*Declaration]GoTypeKind, len(simplePlans)),
	}
	for planIndex := range simplePlans {
		plan := &simplePlans[planIndex]
		simpleRenderer.plans[plan.Declaration] = plan.Definition
	}

	renderer := complexTypeRenderer{
		index:          index,
		names:          names,
		simpleRenderer: simpleRenderer,
		packageName:    packageName,
		usedTypeNames:  make(map[string]string),
		orderedContent: orderedContentTypes,
	}
	for _, declaration := range names.Declarations() {
		name, found := names.Lookup(declaration)
		if !found {
			panic("xsdgen: missing Go name for indexed type")
		}
		renderer.usedTypeNames[name] = describeDeclaration(declaration)
	}

	var body bytes.Buffer
	for planIndex := range complexPlans {
		if err := renderer.renderPlan(
			&body,
			&complexPlans[planIndex],
		); err != nil {
			return nil, err
		}
	}
	for _, choice := range renderer.choices {
		renderer.renderChoice(&body, choice)
	}

	var source bytes.Buffer
	source.WriteString("// Code generated by xsdgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&source, "package %s\n\n", packageName)
	if len(renderer.choices) != 0 {
		source.WriteString("import (\n")
		source.WriteString("\t\"encoding/xml\"\n")
		source.WriteString("\t\"fmt\"\n")
		source.WriteString(")\n\n")
	}
	source.Write(body.Bytes())

	result, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf(
			"xsdgen: format generated complex types: %w",
			err,
		)
	}

	return result, nil
}

func resolveOrderedContentTypes(
	index *Index,
	names []QName,
) (map[*Declaration]struct{}, error) {
	result := make(map[*Declaration]struct{}, len(names))

	for _, name := range names {
		declaration, found := index.LookupType(QName{
			Namespace: name.Namespace,
			Local:     name.Local,
		})
		if !found {
			return nil, &UnresolvedReferenceError{
				Space:   TypeSymbolSpace,
				Lexical: name.String(),
				Name:    name,
				From:    "ordered complex content",
			}
		}
		if declaration.Kind != DeclarationComplexType {
			return nil, fmt.Errorf(
				"%w: ordered content type %s is %s",
				ErrUnsupportedComplexGeneration,
				formatExpandedName(declaration.Name),
				declaration.Kind,
			)
		}

		result[declaration] = struct{}{}
	}

	return result, nil
}

type complexTypeRenderer struct {
	index          *Index
	names          *TypeNames
	simpleRenderer *simpleTypeRenderer
	packageName    string
	choices        []*complexChoice
	usedTypeNames  map[string]string
	orderedContent map[*Declaration]struct{}
	nameInline     bool
	inlineTypes    []*inlineComplexType
}

type inlineComplexType struct {
	name      string
	structure *complexStructure
}

type complexFieldKind uint8

const (
	complexFieldElement complexFieldKind = iota + 1
	complexFieldChoice
	complexFieldAttribute
)

type complexField struct {
	kind              complexFieldKind
	name              QName
	goName            string
	goType            string
	required          bool
	repeated          bool
	nillable          bool
	description       string
	choice            *complexChoice
	constraint        *ValueConstraint
	constraintLiteral string
}

type particleContext struct {
	required bool
	repeated bool
}

type complexStructure struct {
	owner      string
	embedded   string
	valueType  string
	mixed      bool
	elements   []complexField
	attributes []complexField

	elementIndexes   map[expandedName]int
	attributeIndexes map[expandedName]int
	choices          map[*ParticlePlan]*complexChoice
	choiceByElement  map[expandedName]*complexChoice
	insertedChoices  map[*complexChoice]bool
}

func (r *complexTypeRenderer) renderPlan(
	target *bytes.Buffer,
	plan *ComplexTypePlan,
) error {
	if plan == nil ||
		plan.Declaration == nil ||
		plan.Definition == nil ||
		plan.GoName == "" {
		return ErrInvalidComplexType
	}

	structure, err := r.buildStructure(
		plan.GoName,
		plan.Definition,
		r.isOrderedContentType(plan.Declaration),
	)
	if err != nil {
		return fmt.Errorf(
			"xsdgen: generate complex type %q: %w",
			plan.Declaration.Name.Local,
			err,
		)
	}

	fmt.Fprintf(
		target,
		"// %s represents the %q XSD complex type.\n",
		plan.GoName,
		plan.Declaration.Name.Local,
	)
	fmt.Fprintf(target, "type %s ", plan.GoName)
	r.renderStructure(target, structure)
	target.WriteString("\n\n")
	r.renderValueConstraintMethods(target, structure)

	return nil
}

func (r *complexTypeRenderer) isOrderedContentType(
	declaration *Declaration,
) bool {
	_, found := r.orderedContent[declaration]
	return found
}

func (r *complexTypeRenderer) buildStructure(
	owner string,
	definition *ComplexTypeDefinition,
	orderedContent ...bool,
) (*complexStructure, error) {
	if definition == nil {
		return nil, ErrInvalidComplexType
	}

	result := &complexStructure{
		owner:            owner,
		elementIndexes:   make(map[expandedName]int),
		attributeIndexes: make(map[expandedName]int),
		choices:          make(map[*ParticlePlan]*complexChoice),
		choiceByElement:  make(map[expandedName]*complexChoice),
		insertedChoices:  make(map[*complexChoice]bool),
	}

	switch definition.Form {
	case ComplexTypeDirect:
	case ComplexTypeSimpleContentExtension,
		ComplexTypeSimpleContentRestriction:
		if definition.Base == nil {
			return nil, ErrInvalidComplexType
		}

		switch definition.Base.Kind {
		case DeclarationBuiltinSimpleType, DeclarationSimpleType:
			valueType, err := r.declarationGoType(definition.Base)
			if err != nil {
				return nil, err
			}
			result.valueType = valueType

		case DeclarationComplexType:
			name, found := r.names.Lookup(definition.Base)
			if !found {
				return nil, fmt.Errorf(
					"%w: missing Go name for %s",
					ErrInvalidComplexType,
					describeDeclaration(definition.Base),
				)
			}
			result.embedded = name

		default:
			return nil, fmt.Errorf(
				"%w: simple content base %s",
				ErrUnsupportedComplexGeneration,
				describeDeclaration(definition.Base),
			)
		}

	case ComplexTypeComplexContentExtension:
		if definition.Base == nil ||
			definition.Base.Kind != DeclarationComplexType {
			return nil, fmt.Errorf(
				"%w: complex content base",
				ErrUnsupportedComplexGeneration,
			)
		}

		name, found := r.names.Lookup(definition.Base)
		if !found {
			return nil, fmt.Errorf(
				"%w: missing Go name for %s",
				ErrInvalidComplexType,
				describeDeclaration(definition.Base),
			)
		}
		result.embedded = name

	case ComplexTypeComplexContentRestriction:
		return nil, fmt.Errorf(
			"%w: complexContent restriction",
			ErrUnsupportedComplexGeneration,
		)

	default:
		return nil, fmt.Errorf(
			"%w: unknown form %q",
			ErrInvalidComplexType,
			definition.Form,
		)
	}

	result.mixed = definition.Mixed
	if result.mixed && result.valueType == "" {
		result.valueType = "string"
	}

	if err := r.planRepeatedChoices(
		result,
		definition.Particle,
		len(orderedContent) != 0 && orderedContent[0],
	); err != nil {
		return nil, err
	}

	if err := r.collectParticle(
		result,
		definition.Particle,
		particleContext{required: true},
	); err != nil {
		return nil, err
	}
	if len(result.insertedChoices) != len(result.choices) {
		return nil, fmt.Errorf(
			"%w: missing ordered content field in %s",
			ErrUnsupportedComplexGeneration,
			owner,
		)
	}

	if definition.AnyAttribute != nil {
		return nil, fmt.Errorf(
			"%w: xs:anyAttribute in %s",
			ErrUnsupportedComplexGeneration,
			owner,
		)
	}

	for attributeIndex := range definition.Attributes {
		attribute := &definition.Attributes[attributeIndex]
		if attribute.Use == AttributeProhibited {
			continue
		}

		goTypeValue, err := r.simpleTypePlanGoType(&attribute.Type)
		if err != nil {
			return nil, fmt.Errorf(
				"xsdgen: resolve attribute %q type: %w",
				attribute.Name.Local,
				err,
			)
		}

		field := complexField{
			kind:        complexFieldAttribute,
			name:        attribute.Name,
			goType:      goTypeValue.Expression,
			required:    attribute.Required(),
			description: "attribute " + formatExpandedName(attribute.Name),
			constraint:  attribute.Constraint,
		}
		if attribute.Constraint != nil {
			field.constraintLiteral, err = enumerationLiteral(
				goTypeValue.Kind,
				attribute.Constraint.Value,
			)
			if err != nil {
				return nil, fmt.Errorf(
					"xsdgen: render %s value %q for attribute %q: %w",
					attribute.Constraint.Kind,
					attribute.Constraint.Value,
					attribute.Name.Local,
					err,
				)
			}
		}
		if err := result.addAttribute(field); err != nil {
			return nil, err
		}
	}

	if err := result.assignFieldNames(); err != nil {
		return nil, err
	}

	return result, nil
}

func (r *complexTypeRenderer) collectParticle(
	structure *complexStructure,
	particle *ParticlePlan,
	context particleContext,
) error {
	if particle == nil {
		return nil
	}

	context.required =
		context.required && particle.Occurrence.Required()
	context.repeated =
		context.repeated || particle.Occurrence.Repeated()

	if choice, found := structure.choices[particle]; found {
		return structure.addChoice(choice)
	}

	switch particle.Kind {
	case ParticleElement:
		if particle.Element == nil {
			return ErrInvalidParticle
		}

		key := expandedName{
			namespace: particle.Element.Name.Namespace,
			local:     particle.Element.Name.Local,
		}
		if choice, found := structure.choiceByElement[key]; found {
			actualType, err := r.elementGoType(
				particle.Element,
				choice.goType,
			)
			if err != nil {
				return err
			}
			variantIndex := choice.variantIndexes[key]
			variant := &choice.variants[variantIndex]
			if actualType != variant.goType {
				return &GoFieldNameCollisionError{
					Owner:  structure.owner,
					Name:   particle.Element.Name.Local,
					First:  variant.description + " of type " + variant.goType,
					Second: "duplicate element of type " + actualType,
				}
			}

			return structure.addChoice(choice)
		}

		goTypeValue, err := r.elementGoType(
			particle.Element,
			structure.owner,
		)
		if err != nil {
			return fmt.Errorf(
				"xsdgen: resolve element %q type: %w",
				particle.Element.Name.Local,
				err,
			)
		}

		field := complexField{
			kind:        complexFieldElement,
			name:        particle.Element.Name,
			goType:      goTypeValue,
			required:    context.required,
			repeated:    context.repeated,
			description: "element " + formatExpandedName(particle.Element.Name),
		}
		if particle.Element.Source != nil {
			field.nillable = particle.Element.Source.Nillable
		}

		return structure.addElement(field)

	case ParticleAll, ParticleSequence:
		for childIndex := range particle.Children {
			if err := r.collectParticle(
				structure,
				&particle.Children[childIndex],
				context,
			); err != nil {
				return err
			}
		}

		return nil

	case ParticleChoice:
		childContext := context
		if len(particle.Children) != 1 {
			childContext.required = false
		}

		for childIndex := range particle.Children {
			if err := r.collectParticle(
				structure,
				&particle.Children[childIndex],
				childContext,
			); err != nil {
				return err
			}
		}

		return nil

	case ParticleGroup:
		return fmt.Errorf(
			"%w: unexpanded group in %s",
			ErrUnsupportedComplexGeneration,
			structure.owner,
		)

	case ParticleAny:
		return fmt.Errorf(
			"%w: xs:any in %s",
			ErrUnsupportedComplexGeneration,
			structure.owner,
		)

	default:
		return fmt.Errorf(
			"%w: unknown particle kind %q",
			ErrInvalidParticle,
			particle.Kind,
		)
	}
}

func (r *complexTypeRenderer) elementGoType(
	element *ElementPlan,
	owner string,
) (string, error) {
	if element == nil {
		return "", ErrInvalidElement
	}

	typePlan := element.Type
	if element.Reference != nil {
		declaration := element.Reference
		if declaration.Kind != DeclarationElement ||
			declaration.Element == nil ||
			declaration.File == nil {
			return "", ErrInvalidElement
		}

		ownerName, err := GoTypeName(declaration.Name.Local)
		if err != nil {
			return "", err
		}

		planner := complexTypePlanner{
			index:        r.index,
			file:         declaration.File,
			ownerName:    declaration.Name.Local,
			ownerGoName:  ownerName,
			expandGroups: true,
		}
		typePlan, err = planner.planElementType(declaration.Element)
		if err != nil {
			return "", err
		}
	}
	if typePlan == nil {
		return "", ErrInvalidElement
	}

	elementName, err := GoTypeName(element.Name.Local)
	if err != nil {
		return "", err
	}

	return r.typePlanGoTypeWithOwner(
		typePlan,
		owner+elementName,
	)
}

func (r *complexTypeRenderer) typePlanGoType(
	plan *TypePlan,
) (string, error) {
	return r.typePlanGoTypeWithOwner(plan, "")
}

func (r *complexTypeRenderer) simpleTypePlanGoType(
	plan *TypePlan,
) (GoType, error) {
	if plan == nil {
		return GoType{}, ErrInvalidAttribute
	}

	switch {
	case plan.Declaration != nil &&
		plan.InlineSimple == nil &&
		plan.InlineComplex == nil:
		if plan.Declaration.Kind != DeclarationBuiltinSimpleType &&
			plan.Declaration.Kind != DeclarationSimpleType {
			return GoType{}, fmt.Errorf(
				"%w: attribute type %s is not simple",
				ErrInvalidAttribute,
				describeDeclaration(plan.Declaration),
			)
		}

		return r.simpleRenderer.memberGoType(
			SimpleTypeMember{Declaration: plan.Declaration},
		)

	case plan.Declaration == nil &&
		plan.InlineSimple != nil &&
		plan.InlineComplex == nil:
		return r.simpleRenderer.definitionGoType(plan.InlineSimple)

	default:
		return GoType{}, ErrInvalidAttribute
	}
}

func (r *complexTypeRenderer) typePlanGoTypeWithOwner(
	plan *TypePlan,
	owner string,
) (string, error) {
	if plan == nil {
		return "", ErrInvalidComplexType
	}

	count := countTrue(
		plan.Declaration != nil,
		plan.InlineSimple != nil,
		plan.InlineComplex != nil,
	)
	if count != 1 {
		return "", ErrInvalidComplexType
	}

	switch {
	case plan.Declaration != nil:
		return r.declarationGoType(plan.Declaration)

	case plan.InlineSimple != nil:
		value, err := r.simpleRenderer.definitionGoType(
			plan.InlineSimple,
		)
		if err != nil {
			return "", err
		}

		return value.Expression, nil

	case plan.InlineComplex != nil:
		inlineOwner := owner
		if inlineOwner == "" {
			inlineOwner = "Inline"
		}
		if r.nameInline {
			description := "anonymous complex type " + inlineOwner
			if err := r.reserveTypeName(
				inlineOwner,
				description,
			); err != nil {
				return "", err
			}

			inlineType := &inlineComplexType{name: inlineOwner}
			r.inlineTypes = append(r.inlineTypes, inlineType)

			structure, err := r.buildStructure(
				inlineOwner,
				plan.InlineComplex,
			)
			if err != nil {
				return "", err
			}
			inlineType.structure = structure

			return inlineOwner, nil
		}

		structure, err := r.buildStructure(
			inlineOwner,
			plan.InlineComplex,
		)
		if err != nil {
			return "", err
		}

		var source bytes.Buffer
		r.renderStructure(&source, structure)

		return source.String(), nil

	default:
		panic("xsdgen: unreachable type plan")
	}
}

func (r *complexTypeRenderer) declarationGoType(
	declaration *Declaration,
) (string, error) {
	if declaration == nil {
		return "", ErrInvalidComplexType
	}

	switch declaration.Kind {
	case DeclarationBuiltinSimpleType, DeclarationSimpleType:
		value, err := r.simpleRenderer.memberGoType(
			SimpleTypeMember{Declaration: declaration},
		)
		if err != nil {
			return "", err
		}

		return value.Expression, nil

	case DeclarationComplexType:
		name, found := r.names.Lookup(declaration)
		if !found {
			return "", fmt.Errorf(
				"%w: missing Go name for %s",
				ErrInvalidComplexType,
				describeDeclaration(declaration),
			)
		}

		return name, nil

	case DeclarationBuiltinComplexType:
		if declaration.Name.Namespace == Namespace &&
			declaration.Name.Local == "anyType" {
			return "any", nil
		}

		return "", fmt.Errorf(
			"%w: %s",
			ErrUnsupportedComplexGeneration,
			describeDeclaration(declaration),
		)

	default:
		return "", fmt.Errorf(
			"%w: %s is not a type",
			ErrInvalidComplexType,
			describeDeclaration(declaration),
		)
	}
}

func (s *complexStructure) addElement(field complexField) error {
	key := expandedName{
		namespace: field.name.Namespace,
		local:     field.name.Local,
	}
	if existingIndex, found := s.elementIndexes[key]; found {
		existing := &s.elements[existingIndex]
		if existing.goType != field.goType {
			return &GoFieldNameCollisionError{
				Owner:  s.owner,
				Name:   field.name.Local,
				First:  existing.description + " of type " + existing.goType,
				Second: field.description + " of type " + field.goType,
			}
		}

		existing.required = existing.required && field.required
		existing.repeated = existing.repeated || field.repeated
		existing.nillable = existing.nillable || field.nillable

		return nil
	}

	s.elementIndexes[key] = len(s.elements)
	s.elements = append(s.elements, field)

	return nil
}

func (s *complexStructure) addAttribute(field complexField) error {
	key := expandedName{
		namespace: field.name.Namespace,
		local:     field.name.Local,
	}
	if existingIndex, found := s.attributeIndexes[key]; found {
		existing := &s.attributes[existingIndex]
		if existing.goType != field.goType {
			return &GoFieldNameCollisionError{
				Owner:  s.owner,
				Name:   field.name.Local,
				First:  existing.description + " of type " + existing.goType,
				Second: field.description + " of type " + field.goType,
			}
		}
		if !equalValueConstraint(
			existing.constraint,
			field.constraint,
		) {
			return fmt.Errorf(
				"%w: conflicting value constraints for attribute %s in %s",
				ErrInvalidAttribute,
				formatExpandedName(field.name),
				s.owner,
			)
		}

		existing.required = existing.required && field.required
		return nil
	}

	s.attributeIndexes[key] = len(s.attributes)
	s.attributes = append(s.attributes, field)

	return nil
}

func equalValueConstraint(
	left *ValueConstraint,
	right *ValueConstraint,
) bool {
	switch {
	case left == nil:
		return right == nil
	case right == nil:
		return false
	default:
		return *left == *right
	}
}

func (s *complexStructure) assignFieldNames() error {
	used := make(map[string]string)
	if s.embedded != "" {
		used[s.embedded] = "embedded base " + s.embedded
	}
	if s.valueType != "" {
		used["Value"] = "character data"
	}

	for fieldIndex := range s.elements {
		field := &s.elements[fieldIndex]
		var name string

		switch field.kind {
		case complexFieldElement:
			var err error
			name, err = GoTypeName(field.name.Local)
			if err != nil {
				return err
			}

		case complexFieldChoice:
			name = "Content"

		default:
			return ErrInvalidComplexType
		}

		if existing, found := used[name]; found {
			return &GoFieldNameCollisionError{
				Owner:  s.owner,
				Name:   name,
				First:  existing,
				Second: field.description,
			}
		}

		field.goName = name
		used[name] = field.description
	}

	for fieldIndex := range s.attributes {
		field := &s.attributes[fieldIndex]
		name, err := GoTypeName(field.name.Local)
		if err != nil {
			return err
		}
		if _, found := used[name]; found {
			name += "Attr"
		}
		if existing, found := used[name]; found {
			return &GoFieldNameCollisionError{
				Owner:  s.owner,
				Name:   name,
				First:  existing,
				Second: field.description,
			}
		}

		field.goName = name
		used[name] = field.description
	}

	for fieldIndex := range s.attributes {
		field := &s.attributes[fieldIndex]
		if field.constraint == nil {
			continue
		}

		methods := []string{"Effective" + field.goName}
		if field.constraint.Kind == ValueFixed {
			methods = append(
				methods,
				field.goName+"MatchesFixed",
			)
		}

		for _, method := range methods {
			if existing, found := used[method]; found {
				return &GoFieldNameCollisionError{
					Owner:  s.owner,
					Name:   method,
					First:  existing,
					Second: "generated value-constraint method",
				}
			}
		}
	}

	return nil
}

func (r *complexTypeRenderer) renderStructure(
	target *bytes.Buffer,
	structure *complexStructure,
) {
	target.WriteString("struct {\n")
	r.renderStructureFields(target, structure)
	target.WriteString("}")
}

func (r *complexTypeRenderer) renderStructureFields(
	target *bytes.Buffer,
	structure *complexStructure,
) {
	if structure.embedded != "" {
		fmt.Fprintf(target, "\t%s\n", structure.embedded)
	}
	if structure.valueType != "" {
		fmt.Fprintf(
			target,
			"\tValue %s `xml:\",chardata\"`\n",
			structure.valueType,
		)
	}

	for fieldIndex := range structure.elements {
		field := &structure.elements[fieldIndex]

		switch field.kind {
		case complexFieldElement:
			fmt.Fprintf(
				target,
				"\t%s %s %s\n",
				field.goName,
				elementFieldType(field),
				xmlStructTag(
					field.name,
					false,
					!field.required && !field.repeated,
				),
			)

		case complexFieldChoice:
			fmt.Fprintf(
				target,
				"\t%s []%s `xml:\",any\"`\n",
				field.goName,
				field.goType,
			)

		default:
			panic("xsdgen: invalid complex element field kind")
		}
	}

	for fieldIndex := range structure.attributes {
		field := &structure.attributes[fieldIndex]
		fmt.Fprintf(
			target,
			"\t%s %s %s\n",
			field.goName,
			attributeFieldType(field),
			xmlStructTag(field.name, true, !field.required),
		)
	}
}

func (r *complexTypeRenderer) renderValueConstraintMethods(
	target *bytes.Buffer,
	structure *complexStructure,
) {
	for fieldIndex := range structure.attributes {
		field := &structure.attributes[fieldIndex]
		if field.constraint == nil {
			continue
		}

		fmt.Fprintf(
			target,
			"// Effective%s returns %s when explicitly present and the XSD %s value %q otherwise.\n",
			field.goName,
			field.goName,
			field.constraint.Kind,
			field.constraint.Value,
		)
		fmt.Fprintf(
			target,
			"func (value *%s) Effective%s() %s {\n",
			structure.owner,
			field.goName,
			field.goType,
		)
		if field.required {
			target.WriteString("\tif value != nil {\n")
			fmt.Fprintf(
				target,
				"\t\treturn value.%s\n",
				field.goName,
			)
			target.WriteString("\t}\n")
		} else {
			fmt.Fprintf(
				target,
				"\tif value != nil && value.%s != nil {\n",
				field.goName,
			)
			fmt.Fprintf(
				target,
				"\t\treturn *value.%s\n",
				field.goName,
			)
			target.WriteString("\t}\n")
		}
		fmt.Fprintf(
			target,
			"\treturn %s\n",
			field.constraintLiteral,
		)
		target.WriteString("}\n\n")

		if field.constraint.Kind != ValueFixed {
			continue
		}

		fmt.Fprintf(
			target,
			"// %sMatchesFixed reports whether %s is absent or equals its XSD fixed value %q.\n",
			field.goName,
			field.goName,
			field.constraint.Value,
		)
		fmt.Fprintf(
			target,
			"func (value *%s) %sMatchesFixed() bool {\n",
			structure.owner,
			field.goName,
		)
		if field.required {
			fmt.Fprintf(
				target,
				"\treturn value == nil || value.%s == %s\n",
				field.goName,
				field.constraintLiteral,
			)
		} else {
			fmt.Fprintf(
				target,
				"\treturn value == nil || value.%s == nil || *value.%s == %s\n",
				field.goName,
				field.goName,
				field.constraintLiteral,
			)
		}
		target.WriteString("}\n\n")
	}
}

func elementFieldType(field *complexField) string {
	if field.repeated {
		return "[]" + field.goType
	}
	if !field.required || field.nillable {
		return "*" + field.goType
	}

	return field.goType
}

func attributeFieldType(field *complexField) string {
	if !field.required {
		return "*" + field.goType
	}

	return field.goType
}

func xmlStructTag(
	name QName,
	attribute bool,
	optional bool,
) string {
	value := name.Local
	if name.Namespace != "" {
		value = name.Namespace + " " + value
	}
	if attribute {
		value += ",attr"
	}
	if optional {
		value += ",omitempty"
	}

	return "`xml:" + strconv.Quote(value) + "`"
}
