package xsdgen

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGenerateSimpleTypes(t *testing.T) {
	t.Parallel()

	file := parseSchemaFile(t, "types.xsd", `
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="amount">
		<xs:restriction base="xs:decimal"/>
	</xs:simpleType>
	<xs:simpleType name="levels">
		<xs:list itemType="xs:positiveInteger"/>
	</xs:simpleType>
	<xs:simpleType name="rank">
		<xs:restriction base="xs:positiveInteger">
			<xs:enumeration value="1"/>
			<xs:enumeration value="2"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="size">
		<xs:union memberTypes="xs:decimal">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="normal"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="state">
		<xs:restriction base="xs:token">
			<xs:enumeration value="open"/>
			<xs:enumeration value="closed"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="sub-state">
		<xs:restriction base="state">
			<xs:enumeration value="open"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>`)

	index, err := NewIndex(&Set{Files: []*SchemaFile{file}})
	require.NoError(t, err)

	actual, err := GenerateSimpleTypes(index, "example")

	require.NoError(t, err)
	assert.Equal(t, `// Code generated by xsdgen; DO NOT EDIT.

package example

// Amount represents the "amount" XSD simple type.
type Amount float64

// Levels represents the "levels" XSD simple type.
type Levels string

// Rank represents the "rank" XSD simple type.
type Rank uint64

const (
	// Rank1 is the "1" value.
	Rank1 Rank = 1
	// Rank2 is the "2" value.
	Rank2 Rank = 2
)

// Size represents the "size" XSD simple type.
type Size string

const (
	// SizeNormal is the "normal" value.
	SizeNormal Size = "normal"
)

// State represents the "state" XSD simple type.
type State string

const (
	// StateOpen is the "open" value.
	StateOpen State = "open"
	// StateClosed is the "closed" value.
	StateClosed State = "closed"
)

// SubState represents the "sub-state" XSD simple type.
type SubState State

const (
	// SubStateOpen is the "open" value.
	SubStateOpen SubState = "open"
)
`, string(actual))
}

func TestGenerateSimpleTypesError(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name        string
		packageName string
		schema      string
		wantErr     error
	}{
		{
			name:        "invalid package name",
			packageName: "music-xml",
			schema: `
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"/>`,
			wantErr: ErrInvalidPackageName,
		},
		{
			name:        "binary enumeration",
			packageName: "musicxml",
			schema: `
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="binary">
		<xs:restriction base="xs:base64Binary">
			<xs:enumeration value="QQ=="/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>`,
			wantErr: ErrUnsupportedEnumerationValue,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			file := parseSchemaFile(t, "types.xsd", test.schema)
			index, err := NewIndex(&Set{
				Files: []*SchemaFile{file},
			})
			require.NoError(t, err)

			actual, err := GenerateSimpleTypes(
				index,
				test.packageName,
			)

			assert.Nil(t, actual)
			assert.ErrorIs(t, err, test.wantErr)
		})
	}
}

func TestGenerateSimpleTypesNilIndex(t *testing.T) {
	t.Parallel()

	actual, err := GenerateSimpleTypes(nil, "musicxml")

	assert.Nil(t, actual)
	assert.ErrorIs(t, err, ErrNilIndex)
}
