package xsdgen

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"go/token"
	"sort"
	"strconv"
)

var ErrInvalidValidationGeneration = errors.New(
	"xsdgen: invalid validation generation",
)

// GenerateValidationSchema generates a complete runtime validation schema for
// all global types and elements in index.
func GenerateValidationSchema(
	index *Index,
	packageName string,
	variableName string,
) ([]byte, error) {
	if index == nil {
		return nil, ErrNilIndex
	}
	if !token.IsIdentifier(packageName) {
		return nil, fmt.Errorf(
			"%w %q",
			ErrInvalidPackageName,
			packageName,
		)
	}
	if !token.IsIdentifier(variableName) {
		return nil, fmt.Errorf(
			"%w: invalid variable name %q",
			ErrInvalidValidationGeneration,
			variableName,
		)
	}

	simplePlans, err := PlanSimpleTypes(index)
	if err != nil {
		return nil, err
	}
	complexPlans, err := PlanExpandedComplexTypes(index)
	if err != nil {
		return nil, err
	}

	renderer := validationSchemaRenderer{index: index}

	var body bytes.Buffer
	fmt.Fprintf(
		&body,
		"var %s = validationSchemaSet{\n",
		variableName,
	)
	body.WriteString(
		"\tTypes: map[validationQName]*validationTypeSchema{\n",
	)
	for planIndex := range simplePlans {
		plan := &simplePlans[planIndex]
		renderValidationQName(&body, plan.Declaration.Name)
		body.WriteString(": {Simple: ")
		if err := renderer.renderSimpleSchema(
			&body,
			plan.Definition,
		); err != nil {
			return nil, fmt.Errorf(
				"xsdgen: render validation for simple type %q: %w",
				plan.Declaration.Name.Local,
				err,
			)
		}
		body.WriteString("},\n")
	}
	for planIndex := range complexPlans {
		plan := &complexPlans[planIndex]
		renderValidationQName(&body, plan.Declaration.Name)
		body.WriteString(": {Complex: ")
		if err := renderer.renderComplexSchema(
			&body,
			plan.Definition,
		); err != nil {
			return nil, fmt.Errorf(
				"xsdgen: render validation for complex type %q: %w",
				plan.Declaration.Name.Local,
				err,
			)
		}
		body.WriteString("},\n")
	}
	body.WriteString("\t},\n")

	body.WriteString(
		"\tElements: map[validationQName]*validationElementSchema{\n",
	)
	for _, declaration := range validationElementDeclarations(index) {
		typePlan, err := renderer.planGlobalElement(declaration)
		if err != nil {
			return nil, err
		}

		renderValidationQName(&body, declaration.Name)
		body.WriteString(": ")
		if err := renderer.renderElementSchema(
			&body,
			&ElementPlan{
				Source: declaration.Element,
				Name:   declaration.Name,
				Type:   typePlan,
			},
		); err != nil {
			return nil, fmt.Errorf(
				"xsdgen: render validation for element %q: %w",
				declaration.Name.Local,
				err,
			)
		}
		body.WriteString(",\n")
	}
	body.WriteString("\t},\n")
	body.WriteString("}\n")

	var source bytes.Buffer
	source.WriteString("// Code generated by xsdgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&source, "package %s\n\n", packageName)
	source.Write(body.Bytes())

	result, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf(
			"xsdgen: format generated validation schema: %w",
			err,
		)
	}

	return result, nil
}

type validationSchemaRenderer struct {
	index *Index
}

func (r *validationSchemaRenderer) planGlobalElement(
	declaration *Declaration,
) (*TypePlan, error) {
	if declaration == nil ||
		declaration.Kind != DeclarationElement ||
		declaration.Element == nil ||
		declaration.File == nil {
		return nil, ErrInvalidElement
	}

	planner := complexTypePlanner{
		index:        r.index,
		file:         declaration.File,
		ownerName:    declaration.Name.Local,
		expandGroups: true,
	}

	return planner.planElementType(declaration.Element)
}

func (r *validationSchemaRenderer) renderSimpleSchema(
	target *bytes.Buffer,
	definition *SimpleTypeDefinition,
) error {
	if definition == nil || definition.Source == nil {
		return ErrInvalidSimpleType
	}

	target.WriteString("&validationSimpleSchema{")
	fmt.Fprintf(
		target,
		"Form: validationSimpleForm(%s),",
		strconv.Quote(string(definition.Form)),
	)

	switch definition.Form {
	case SimpleTypeRestriction:
		if definition.Base == nil ||
			definition.Source.Restriction == nil {
			return ErrInvalidSimpleType
		}
		target.WriteString("Base: ")
		if err := r.renderSimpleMember(target, definition.Base); err != nil {
			return err
		}
		target.WriteString(",")
		if len(definition.Enumerations) != 0 {
			target.WriteString("Enumerations: []string{")
			for _, enumeration := range definition.Enumerations {
				fmt.Fprintf(
					target,
					"%s,",
					strconv.Quote(enumeration.Value),
				)
			}
			target.WriteString("},")
		}

		restriction := definition.Source.Restriction
		if len(restriction.Patterns) != 0 {
			target.WriteString("Patterns: []string{")
			for _, pattern := range restriction.Patterns {
				fmt.Fprintf(
					target,
					"%s,",
					strconv.Quote(pattern.Value),
				)
			}
			target.WriteString("},")
		}
		if err := renderValidationFacets(target, restriction); err != nil {
			return err
		}

	case SimpleTypeUnion:
		if len(definition.Members) == 0 {
			return ErrInvalidSimpleType
		}
		target.WriteString("Members: []*validationSimpleMember{")
		for memberIndex := range definition.Members {
			if err := r.renderSimpleMember(
				target,
				&definition.Members[memberIndex],
			); err != nil {
				return err
			}
			target.WriteString(",")
		}
		target.WriteString("},")

	case SimpleTypeList:
		if definition.Item == nil {
			return ErrInvalidSimpleType
		}
		target.WriteString("Item: ")
		if err := r.renderSimpleMember(target, definition.Item); err != nil {
			return err
		}
		target.WriteString(",")

	default:
		return ErrInvalidSimpleType
	}

	target.WriteString("}")
	return nil
}

func (r *validationSchemaRenderer) renderSimpleMember(
	target *bytes.Buffer,
	member *SimpleTypeMember,
) error {
	if member == nil {
		return ErrInvalidSimpleType
	}

	target.WriteString("&validationSimpleMember{")
	switch {
	case member.Declaration != nil && member.Inline == nil:
		target.WriteString("Name: ")
		renderValidationQName(target, member.Declaration.Name)
	case member.Declaration == nil && member.Inline != nil:
		target.WriteString("Inline: ")
		if err := r.renderSimpleSchema(target, member.Inline); err != nil {
			return err
		}
	default:
		return ErrInvalidSimpleType
	}
	target.WriteString("}")

	return nil
}

func renderValidationFacets(
	target *bytes.Buffer,
	restriction *Restriction,
) error {
	if restriction == nil {
		return ErrInvalidSimpleType
	}

	stringFacets := []struct {
		name  string
		facet *Facet
	}{
		{"MinInclusive", restriction.MinInclusive},
		{"MaxInclusive", restriction.MaxInclusive},
		{"MinExclusive", restriction.MinExclusive},
		{"MaxExclusive", restriction.MaxExclusive},
	}
	for _, value := range stringFacets {
		if value.facet == nil {
			continue
		}
		fmt.Fprintf(
			target,
			"%s: %s, Has%s: true,",
			value.name,
			strconv.Quote(value.facet.Value),
			value.name,
		)
	}

	unsignedFacets := []struct {
		name  string
		facet *Facet
	}{
		{"Length", restriction.Length},
		{"MinLength", restriction.MinLength},
		{"MaxLength", restriction.MaxLength},
		{"TotalDigits", restriction.TotalDigits},
		{"FractionDigits", restriction.FractionDigits},
	}
	for _, value := range unsignedFacets {
		if value.facet == nil {
			continue
		}
		number, err := strconv.ParseUint(value.facet.Value, 10, 64)
		if err != nil {
			return fmt.Errorf(
				"%w: invalid %s value %q",
				ErrInvalidSimpleType,
				value.name,
				value.facet.Value,
			)
		}
		fmt.Fprintf(
			target,
			"%s: %d, Has%s: true,",
			value.name,
			number,
			value.name,
		)
	}

	if restriction.WhiteSpace != nil {
		fmt.Fprintf(
			target,
			"WhiteSpace: %s,",
			strconv.Quote(restriction.WhiteSpace.Value),
		)
	}

	return nil
}

func (r *validationSchemaRenderer) renderComplexSchema(
	target *bytes.Buffer,
	definition *ComplexTypeDefinition,
) error {
	if definition == nil {
		return ErrInvalidComplexType
	}

	target.WriteString("&validationComplexSchema{")
	fmt.Fprintf(
		target,
		"Form: validationComplexForm(%s),",
		strconv.Quote(string(definition.Form)),
	)
	if definition.Base != nil {
		target.WriteString("Base: &validationTypeRef{Name: ")
		renderValidationQName(target, definition.Base.Name)
		target.WriteString("},")
	}
	if definition.Particle != nil {
		target.WriteString("Particle: ")
		if err := r.renderParticleSchema(
			target,
			definition.Particle,
		); err != nil {
			return err
		}
		target.WriteString(",")
	}
	if len(definition.Attributes) != 0 {
		target.WriteString("Attributes: []validationAttributeSchema{")
		for attributeIndex := range definition.Attributes {
			if err := r.renderAttributeSchema(
				target,
				&definition.Attributes[attributeIndex],
			); err != nil {
				return err
			}
			target.WriteString(",")
		}
		target.WriteString("},")
	}
	if definition.AnyAttribute != nil {
		target.WriteString("AnyAttribute: ")
		renderValidationAnyAttribute(
			target,
			definition.AnyAttribute,
		)
		target.WriteString(",")
	}
	if definition.Mixed {
		target.WriteString("Mixed: true,")
	}
	target.WriteString("}")

	return nil
}

func (r *validationSchemaRenderer) renderParticleSchema(
	target *bytes.Buffer,
	particle *ParticlePlan,
) error {
	if particle == nil {
		return ErrInvalidParticle
	}

	target.WriteString("&validationParticleSchema{")
	fmt.Fprintf(
		target,
		"Kind: validationParticleKind(%s),",
		strconv.Quote(string(particle.Kind)),
	)
	target.WriteString("Occurrence: ")
	renderValidationOccurrence(target, particle.Occurrence)
	target.WriteString(",")

	switch particle.Kind {
	case ParticleElement:
		if particle.Element == nil {
			return ErrInvalidElement
		}
		target.WriteString("Element: ")
		if err := r.renderElementSchema(
			target,
			particle.Element,
		); err != nil {
			return err
		}
		target.WriteString(",")

	case ParticleAll, ParticleChoice, ParticleSequence:
		target.WriteString("Children: []*validationParticleSchema{")
		for childIndex := range particle.Children {
			if err := r.renderParticleSchema(
				target,
				&particle.Children[childIndex],
			); err != nil {
				return err
			}
			target.WriteString(",")
		}
		target.WriteString("},")

	case ParticleAny:
		if particle.Source == nil ||
			particle.Source.Any == nil {
			return ErrInvalidParticle
		}
		target.WriteString("Any: &validationAnySchema{")
		fmt.Fprintf(
			target,
			"Namespace: %s, ProcessContents: %s,",
			strconv.Quote(particle.Source.Any.Namespace),
			strconv.Quote(particle.Source.Any.ProcessContents),
		)
		target.WriteString("},")

	case ParticleGroup:
		return fmt.Errorf(
			"%w: unexpanded group",
			ErrInvalidValidationGeneration,
		)

	default:
		return ErrInvalidParticle
	}

	target.WriteString("}")
	return nil
}

func (r *validationSchemaRenderer) renderElementSchema(
	target *bytes.Buffer,
	element *ElementPlan,
) error {
	if element == nil || element.Source == nil {
		return ErrInvalidElement
	}

	target.WriteString("&validationElementSchema{")
	target.WriteString("Name: ")
	renderValidationQName(target, element.Name)
	target.WriteString(",")

	if element.Reference != nil {
		target.WriteString("Reference: ")
		renderValidationQName(target, element.Reference.Name)
		target.WriteString(",")
	} else {
		if element.Type == nil {
			return ErrInvalidElement
		}
		target.WriteString("Type: ")
		if err := r.renderTypeRef(target, element.Type); err != nil {
			return err
		}
		target.WriteString(",")
	}

	if element.Source.Default != nil {
		fmt.Fprintf(
			target,
			"Default: validationString(%s),",
			strconv.Quote(*element.Source.Default),
		)
	}
	if element.Source.Fixed != nil {
		fmt.Fprintf(
			target,
			"Fixed: validationString(%s),",
			strconv.Quote(*element.Source.Fixed),
		)
	}
	if element.Source.Nillable {
		target.WriteString("Nillable: true,")
	}
	if element.Source.Abstract {
		target.WriteString("Abstract: true,")
	}
	target.WriteString("}")

	return nil
}

func (r *validationSchemaRenderer) renderAttributeSchema(
	target *bytes.Buffer,
	attribute *AttributePlan,
) error {
	if attribute == nil {
		return ErrInvalidAttribute
	}

	target.WriteString("validationAttributeSchema{Name: ")
	renderValidationQName(target, attribute.Name)
	target.WriteString(", Type: ")
	if err := r.renderTypeRef(target, &attribute.Type); err != nil {
		return err
	}
	fmt.Fprintf(
		target,
		", Use: validationAttributeUse(%s),",
		strconv.Quote(string(attribute.Use)),
	)
	if attribute.Constraint != nil {
		fmt.Fprintf(
			target,
			"Constraint: &validationValueConstraint{Kind: %s, Value: %s},",
			strconv.Quote(string(attribute.Constraint.Kind)),
			strconv.Quote(attribute.Constraint.Value),
		)
	}
	target.WriteString("}")

	return nil
}

func (r *validationSchemaRenderer) renderTypeRef(
	target *bytes.Buffer,
	plan *TypePlan,
) error {
	if plan == nil {
		return ErrInvalidComplexType
	}

	target.WriteString("validationTypeRef{")
	switch {
	case plan.Declaration != nil &&
		plan.InlineSimple == nil &&
		plan.InlineComplex == nil:
		target.WriteString("Name: ")
		renderValidationQName(target, plan.Declaration.Name)

	case plan.Declaration == nil &&
		plan.InlineSimple != nil &&
		plan.InlineComplex == nil:
		target.WriteString("InlineSimple: ")
		if err := r.renderSimpleSchema(
			target,
			plan.InlineSimple,
		); err != nil {
			return err
		}

	case plan.Declaration == nil &&
		plan.InlineSimple == nil &&
		plan.InlineComplex != nil:
		target.WriteString("InlineComplex: ")
		if err := r.renderComplexSchema(
			target,
			plan.InlineComplex,
		); err != nil {
			return err
		}

	default:
		return ErrInvalidComplexType
	}
	target.WriteString("}")

	return nil
}

func renderValidationQName(
	target *bytes.Buffer,
	name QName,
) {
	fmt.Fprintf(
		target,
		"validationQName{Space: %s, Local: %s}",
		strconv.Quote(name.Namespace),
		strconv.Quote(name.Local),
	)
}

func renderValidationOccurrence(
	target *bytes.Buffer,
	occurrence OccurrenceRange,
) {
	fmt.Fprintf(
		target,
		"validationOccurrence{Min: %d, Max: %d, Unbounded: %t}",
		occurrence.Min,
		occurrence.Max,
		occurrence.Unbounded,
	)
}

func renderValidationAnyAttribute(
	target *bytes.Buffer,
	attribute *AnyAttribute,
) {
	fmt.Fprintf(
		target,
		"&validationAnyAttributeSchema{Namespace: %s, ProcessContents: %s}",
		strconv.Quote(attribute.Namespace),
		strconv.Quote(attribute.ProcessContents),
	)
}

func validationElementDeclarations(
	index *Index,
) []*Declaration {
	result := make([]*Declaration, 0, len(index.elements))
	for _, declaration := range index.elements {
		result = append(result, declaration)
	}
	sort.Slice(result, func(left int, right int) bool {
		if result[left].Name.Namespace != result[right].Name.Namespace {
			return result[left].Name.Namespace <
				result[right].Name.Namespace
		}
		return result[left].Name.Local < result[right].Name.Local
	})
	return result
}
