package xsdgen

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGenerateComplexTypes(t *testing.T) {
	t.Parallel()

	file := parseSchemaFile(t, "types.xsd", `
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:s="urn:score"
	targetNamespace="urn:score"
	elementFormDefault="qualified">
	<xs:simpleType name="label">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:element name="shared" type="s:label"/>
	<xs:attribute name="shared-attribute" type="xs:integer"/>
	<xs:complexType name="base">
		<xs:sequence>
			<xs:element name="title" type="xs:string"/>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="alpha" type="s:label"/>
				<xs:element name="beta" type="xs:int"/>
			</xs:choice>
			<xs:element ref="s:shared" minOccurs="0"/>
			<xs:element name="inline" minOccurs="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="s:label">
							<xs:attribute
								name="code"
								type="xs:string"
								use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="title" type="xs:token"/>
		<xs:attribute
			ref="s:shared-attribute"
			use="required"/>
	</xs:complexType>
	<xs:complexType name="derived">
		<xs:complexContent>
			<xs:extension base="s:base">
				<xs:attribute name="extra" type="xs:boolean"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="formatted">
		<xs:simpleContent>
			<xs:extension base="s:label">
				<xs:attribute name="lang" type="xs:language"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>`)

	index, err := NewIndex(&Set{Files: []*SchemaFile{file}})
	require.NoError(t, err)

	actual, err := GenerateComplexTypes(index, "example")

	require.NoError(t, err)
	assert.Equal(t, `// Code generated by xsdgen; DO NOT EDIT.

package example

import (
	"encoding/xml"
	"fmt"
)

// Base represents the "base" XSD complex type.
type Base struct {
	Title   string       `+"`xml:\"urn:score title\"`"+`
	Content BaseContents `+"`xml:\",any\"`"+`
	Shared  *Label       `+"`xml:\"urn:score shared,omitempty\"`"+`
	Inline  *struct {
		Value Label  `+"`xml:\",chardata\"`"+`
		Code  string `+"`xml:\"code,attr\"`"+`
	} `+"`xml:\"urn:score inline,omitempty\"`"+`
	TitleAttr       *string `+"`xml:\"title,attr,omitempty\"`"+`
	SharedAttribute int64   `+"`xml:\"urn:score shared-attribute,attr\"`"+`
}

// Derived represents the "derived" XSD complex type.
type Derived struct {
	Base
	Extra *bool `+"`xml:\"extra,attr,omitempty\"`"+`
}

// Formatted represents the "formatted" XSD complex type.
type Formatted struct {
	Value Label   `+"`xml:\",chardata\"`"+`
	Lang  *string `+"`xml:\"lang,attr,omitempty\"`"+`
}

// BaseContents stores the recognized ordered child elements of Base.
type BaseContents []BaseContent

// UnmarshalXML decodes and appends one recognized Base child.
func (values *BaseContents) UnmarshalXML(
	decoder *xml.Decoder,
	start xml.StartElement,
) error {
	var decoded BaseContent
	if err := decoded.UnmarshalXML(decoder, start); err != nil {
		return err
	}
	if decoded == (BaseContent{}) {
		return nil
	}
	*values = append(*values, decoded)
	return nil
}

// BaseContent is one ordered child element of Base.
type BaseContent struct {
	Alpha *Label
	Beta  *int32
}

// AddAlpha appends the "alpha" child while preserving content order.
func (value *Base) AddAlpha(element *Label) *Label {
	value.Content = append(value.Content, BaseContent{Alpha: element})
	return element
}

// AddBeta appends the "beta" child while preserving content order.
func (value *Base) AddBeta(element *int32) *int32 {
	value.Content = append(value.Content, BaseContent{Beta: element})
	return element
}

// UnmarshalXML decodes one BaseContent variant.
func (value *BaseContent) UnmarshalXML(
	decoder *xml.Decoder,
	start xml.StartElement,
) error {
	*value = BaseContent{}

	switch start.Name {
	case (xml.Name{Space: "urn:score", Local: "alpha"}):
		var decoded Label
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("example: decode BaseContent.Alpha: %w", err)
		}
		value.Alpha = &decoded
		return nil

	case (xml.Name{Space: "urn:score", Local: "beta"}):
		var decoded int32
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("example: decode BaseContent.Beta: %w", err)
		}
		value.Beta = &decoded
		return nil

	default:
		if err := decoder.Skip(); err != nil {
			return fmt.Errorf("example: skip unsupported BaseContent element: %w", err)
		}
		return nil
	}
}

// MarshalXML encodes the selected BaseContent variant.
func (value BaseContent) MarshalXML(
	encoder *xml.Encoder,
	_ xml.StartElement,
) error {
	selected := 0
	if value.Alpha != nil {
		selected++
	}
	if value.Beta != nil {
		selected++
	}
	if selected != 1 {
		return fmt.Errorf("example: BaseContent must contain exactly one value, got %d", selected)
	}

	switch {
	case value.Alpha != nil:
		start := xml.StartElement{Name: xml.Name{Space: "urn:score", Local: "alpha"}}
		if err := encoder.EncodeElement(value.Alpha, start); err != nil {
			return fmt.Errorf("example: encode BaseContent.Alpha: %w", err)
		}
		return nil
	case value.Beta != nil:
		start := xml.StartElement{Name: xml.Name{Space: "urn:score", Local: "beta"}}
		if err := encoder.EncodeElement(value.Beta, start); err != nil {
			return fmt.Errorf("example: encode BaseContent.Beta: %w", err)
		}
		return nil
	}

	return nil
}
`, string(actual))
}

func TestGenerateComplexTypesOrdersFieldsFromParticle(t *testing.T) {
	t.Parallel()

	file := parseSchemaFile(t, "types.xsd", `
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="record">
		<xs:choice>
			<xs:sequence>
				<xs:element name="alpha" type="xs:string"/>
				<xs:element name="charlie" type="xs:string"/>
			</xs:sequence>
			<xs:sequence>
				<xs:element name="bravo" type="xs:string"/>
				<xs:element name="alpha" type="xs:string"/>
			</xs:sequence>
		</xs:choice>
	</xs:complexType>
</xs:schema>`)
	index, err := NewIndex(&Set{Files: []*SchemaFile{file}})
	require.NoError(t, err)

	actual, err := GenerateComplexTypes(index, "example")
	require.NoError(t, err)

	source := string(actual)
	bravo := strings.Index(source, "\tBravo")
	alpha := strings.Index(source, "\tAlpha")
	charlie := strings.Index(source, "\tCharlie")
	require.NotEqual(t, -1, bravo)
	require.NotEqual(t, -1, alpha)
	require.NotEqual(t, -1, charlie)
	assert.Less(t, bravo, alpha)
	assert.Less(t, alpha, charlie)
}

func TestGenerateComplexTypesOrderedRepeatedSequence(t *testing.T) {
	t.Parallel()

	file := parseSchemaFile(t, "types.xsd", `
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="record">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="alpha" type="xs:string"/>
			<xs:element name="beta" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>`)
	index, err := NewIndex(&Set{Files: []*SchemaFile{file}})
	require.NoError(t, err)

	actual, err := GenerateComplexTypes(index, "example")
	require.NoError(t, err)

	source := string(actual)
	assert.Contains(t, source, "Content RecordContents")
	assert.Contains(t, source, "type RecordContents []RecordContent")
	assert.Contains(t, source, "func (value *Record) AddAlpha(")
	assert.Contains(t, source, "func (value *Record) AddBeta(")
}

func TestGenerateComplexTypesError(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name        string
		packageName string
		schema      string
		wantErr     error
	}{
		{
			name:        "invalid package name",
			packageName: "music-xml",
			schema: `
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"/>`,
			wantErr: ErrInvalidPackageName,
		},
		{
			name:        "field name collision",
			packageName: "musicxml",
			schema: `
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="record">
		<xs:sequence>
			<xs:element name="foo-bar" type="xs:string"/>
			<xs:element name="foo_bar" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>`,
			wantErr: ErrGoFieldNameCollision,
		},
		{
			name:        "any particle",
			packageName: "musicxml",
			schema: `
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="record">
		<xs:sequence>
			<xs:any/>
		</xs:sequence>
			</xs:complexType>
</xs:schema>`,
			wantErr: ErrUnsupportedComplexGeneration,
		},
		{
			name:        "multiple repeated choices",
			packageName: "musicxml",
			schema: `
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="record">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="alpha" type="xs:string"/>
				<xs:element name="beta" type="xs:string"/>
			</xs:choice>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="gamma" type="xs:string"/>
				<xs:element name="delta" type="xs:string"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
</xs:schema>`,
			wantErr: ErrUnsupportedComplexGeneration,
		},
		{
			name:        "element at multiple ordered positions",
			packageName: "musicxml",
			schema: `
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="record">
		<xs:sequence>
			<xs:element name="alpha" type="xs:string"/>
			<xs:element name="beta" type="xs:string"/>
			<xs:element name="alpha" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>`,
			wantErr: ErrAmbiguousComplexContent,
		},
		{
			name:        "ordered content field collision",
			packageName: "musicxml",
			schema: `
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="record">
		<xs:sequence>
			<xs:element name="content" type="xs:string"/>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="alpha" type="xs:string"/>
				<xs:element name="beta" type="xs:string"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
</xs:schema>`,
			wantErr: ErrGoFieldNameCollision,
		},
		{
			name:        "ordered content type collision",
			packageName: "musicxml",
			schema: `
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="record">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="alpha" type="xs:string"/>
			<xs:element name="beta" type="xs:string"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="record-content"/>
</xs:schema>`,
			wantErr: ErrGoNameCollision,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()

			file := parseSchemaFile(t, "types.xsd", test.schema)
			index, err := NewIndex(&Set{
				Files: []*SchemaFile{file},
			})
			require.NoError(t, err)

			actual, err := GenerateComplexTypes(
				index,
				test.packageName,
			)

			assert.Nil(t, actual)
			assert.ErrorIs(t, err, test.wantErr)
		})
	}
}

func TestGenerateComplexTypesNilIndex(t *testing.T) {
	t.Parallel()

	actual, err := GenerateComplexTypes(nil, "musicxml")

	assert.Nil(t, actual)
	assert.ErrorIs(t, err, ErrNilIndex)
}
