// Code generated by xsdgen; DO NOT EDIT.

package musicxml

// AboveBelow represents the "above-below" XSD simple type.
type AboveBelow string

const (
	// AboveBelowAbove is the "above" value.
	AboveBelowAbove AboveBelow = "above"
	// AboveBelowBelow is the "below" value.
	AboveBelowBelow AboveBelow = "below"
)

// AccidentalValue represents the "accidental-value" XSD simple type.
type AccidentalValue string

const (
	// AccidentalValueSharp is the "sharp" value.
	AccidentalValueSharp AccidentalValue = "sharp"
	// AccidentalValueNatural is the "natural" value.
	AccidentalValueNatural AccidentalValue = "natural"
	// AccidentalValueFlat is the "flat" value.
	AccidentalValueFlat AccidentalValue = "flat"
	// AccidentalValueDoubleSharp is the "double-sharp" value.
	AccidentalValueDoubleSharp AccidentalValue = "double-sharp"
	// AccidentalValueSharpSharp is the "sharp-sharp" value.
	AccidentalValueSharpSharp AccidentalValue = "sharp-sharp"
	// AccidentalValueFlatFlat is the "flat-flat" value.
	AccidentalValueFlatFlat AccidentalValue = "flat-flat"
	// AccidentalValueNaturalSharp is the "natural-sharp" value.
	AccidentalValueNaturalSharp AccidentalValue = "natural-sharp"
	// AccidentalValueNaturalFlat is the "natural-flat" value.
	AccidentalValueNaturalFlat AccidentalValue = "natural-flat"
	// AccidentalValueQuarterFlat is the "quarter-flat" value.
	AccidentalValueQuarterFlat AccidentalValue = "quarter-flat"
	// AccidentalValueQuarterSharp is the "quarter-sharp" value.
	AccidentalValueQuarterSharp AccidentalValue = "quarter-sharp"
	// AccidentalValueThreeQuartersFlat is the "three-quarters-flat" value.
	AccidentalValueThreeQuartersFlat AccidentalValue = "three-quarters-flat"
	// AccidentalValueThreeQuartersSharp is the "three-quarters-sharp" value.
	AccidentalValueThreeQuartersSharp AccidentalValue = "three-quarters-sharp"
	// AccidentalValueSharpDown is the "sharp-down" value.
	AccidentalValueSharpDown AccidentalValue = "sharp-down"
	// AccidentalValueSharpUp is the "sharp-up" value.
	AccidentalValueSharpUp AccidentalValue = "sharp-up"
	// AccidentalValueNaturalDown is the "natural-down" value.
	AccidentalValueNaturalDown AccidentalValue = "natural-down"
	// AccidentalValueNaturalUp is the "natural-up" value.
	AccidentalValueNaturalUp AccidentalValue = "natural-up"
	// AccidentalValueFlatDown is the "flat-down" value.
	AccidentalValueFlatDown AccidentalValue = "flat-down"
	// AccidentalValueFlatUp is the "flat-up" value.
	AccidentalValueFlatUp AccidentalValue = "flat-up"
	// AccidentalValueDoubleSharpDown is the "double-sharp-down" value.
	AccidentalValueDoubleSharpDown AccidentalValue = "double-sharp-down"
	// AccidentalValueDoubleSharpUp is the "double-sharp-up" value.
	AccidentalValueDoubleSharpUp AccidentalValue = "double-sharp-up"
	// AccidentalValueFlatFlatDown is the "flat-flat-down" value.
	AccidentalValueFlatFlatDown AccidentalValue = "flat-flat-down"
	// AccidentalValueFlatFlatUp is the "flat-flat-up" value.
	AccidentalValueFlatFlatUp AccidentalValue = "flat-flat-up"
	// AccidentalValueArrowDown is the "arrow-down" value.
	AccidentalValueArrowDown AccidentalValue = "arrow-down"
	// AccidentalValueArrowUp is the "arrow-up" value.
	AccidentalValueArrowUp AccidentalValue = "arrow-up"
	// AccidentalValueTripleSharp is the "triple-sharp" value.
	AccidentalValueTripleSharp AccidentalValue = "triple-sharp"
	// AccidentalValueTripleFlat is the "triple-flat" value.
	AccidentalValueTripleFlat AccidentalValue = "triple-flat"
	// AccidentalValueSlashQuarterSharp is the "slash-quarter-sharp" value.
	AccidentalValueSlashQuarterSharp AccidentalValue = "slash-quarter-sharp"
	// AccidentalValueSlashSharp is the "slash-sharp" value.
	AccidentalValueSlashSharp AccidentalValue = "slash-sharp"
	// AccidentalValueSlashFlat is the "slash-flat" value.
	AccidentalValueSlashFlat AccidentalValue = "slash-flat"
	// AccidentalValueDoubleSlashFlat is the "double-slash-flat" value.
	AccidentalValueDoubleSlashFlat AccidentalValue = "double-slash-flat"
	// AccidentalValueSharp1 is the "sharp-1" value.
	AccidentalValueSharp1 AccidentalValue = "sharp-1"
	// AccidentalValueSharp2 is the "sharp-2" value.
	AccidentalValueSharp2 AccidentalValue = "sharp-2"
	// AccidentalValueSharp3 is the "sharp-3" value.
	AccidentalValueSharp3 AccidentalValue = "sharp-3"
	// AccidentalValueSharp5 is the "sharp-5" value.
	AccidentalValueSharp5 AccidentalValue = "sharp-5"
	// AccidentalValueFlat1 is the "flat-1" value.
	AccidentalValueFlat1 AccidentalValue = "flat-1"
	// AccidentalValueFlat2 is the "flat-2" value.
	AccidentalValueFlat2 AccidentalValue = "flat-2"
	// AccidentalValueFlat3 is the "flat-3" value.
	AccidentalValueFlat3 AccidentalValue = "flat-3"
	// AccidentalValueFlat4 is the "flat-4" value.
	AccidentalValueFlat4 AccidentalValue = "flat-4"
	// AccidentalValueSori is the "sori" value.
	AccidentalValueSori AccidentalValue = "sori"
	// AccidentalValueKoron is the "koron" value.
	AccidentalValueKoron AccidentalValue = "koron"
	// AccidentalValueOther is the "other" value.
	AccidentalValueOther AccidentalValue = "other"
)

// AccordionMiddle represents the "accordion-middle" XSD simple type.
type AccordionMiddle uint64

// ArrowDirection represents the "arrow-direction" XSD simple type.
type ArrowDirection string

const (
	// ArrowDirectionLeft is the "left" value.
	ArrowDirectionLeft ArrowDirection = "left"
	// ArrowDirectionUp is the "up" value.
	ArrowDirectionUp ArrowDirection = "up"
	// ArrowDirectionRight is the "right" value.
	ArrowDirectionRight ArrowDirection = "right"
	// ArrowDirectionDown is the "down" value.
	ArrowDirectionDown ArrowDirection = "down"
	// ArrowDirectionNorthwest is the "northwest" value.
	ArrowDirectionNorthwest ArrowDirection = "northwest"
	// ArrowDirectionNortheast is the "northeast" value.
	ArrowDirectionNortheast ArrowDirection = "northeast"
	// ArrowDirectionSoutheast is the "southeast" value.
	ArrowDirectionSoutheast ArrowDirection = "southeast"
	// ArrowDirectionSouthwest is the "southwest" value.
	ArrowDirectionSouthwest ArrowDirection = "southwest"
	// ArrowDirectionLeftRight is the "left right" value.
	ArrowDirectionLeftRight ArrowDirection = "left right"
	// ArrowDirectionUpDown is the "up down" value.
	ArrowDirectionUpDown ArrowDirection = "up down"
	// ArrowDirectionNorthwestSoutheast is the "northwest southeast" value.
	ArrowDirectionNorthwestSoutheast ArrowDirection = "northwest southeast"
	// ArrowDirectionNortheastSouthwest is the "northeast southwest" value.
	ArrowDirectionNortheastSouthwest ArrowDirection = "northeast southwest"
	// ArrowDirectionOther is the "other" value.
	ArrowDirectionOther ArrowDirection = "other"
)

// ArrowStyle represents the "arrow-style" XSD simple type.
type ArrowStyle string

const (
	// ArrowStyleSingle is the "single" value.
	ArrowStyleSingle ArrowStyle = "single"
	// ArrowStyleDouble is the "double" value.
	ArrowStyleDouble ArrowStyle = "double"
	// ArrowStyleFilled is the "filled" value.
	ArrowStyleFilled ArrowStyle = "filled"
	// ArrowStyleHollow is the "hollow" value.
	ArrowStyleHollow ArrowStyle = "hollow"
	// ArrowStylePaired is the "paired" value.
	ArrowStylePaired ArrowStyle = "paired"
	// ArrowStyleCombined is the "combined" value.
	ArrowStyleCombined ArrowStyle = "combined"
	// ArrowStyleOther is the "other" value.
	ArrowStyleOther ArrowStyle = "other"
)

// BackwardForward represents the "backward-forward" XSD simple type.
type BackwardForward string

const (
	// BackwardForwardBackward is the "backward" value.
	BackwardForwardBackward BackwardForward = "backward"
	// BackwardForwardForward is the "forward" value.
	BackwardForwardForward BackwardForward = "forward"
)

// BarStyle represents the "bar-style" XSD simple type.
type BarStyle string

const (
	// BarStyleRegular is the "regular" value.
	BarStyleRegular BarStyle = "regular"
	// BarStyleDotted is the "dotted" value.
	BarStyleDotted BarStyle = "dotted"
	// BarStyleDashed is the "dashed" value.
	BarStyleDashed BarStyle = "dashed"
	// BarStyleHeavy is the "heavy" value.
	BarStyleHeavy BarStyle = "heavy"
	// BarStyleLightLight is the "light-light" value.
	BarStyleLightLight BarStyle = "light-light"
	// BarStyleLightHeavy is the "light-heavy" value.
	BarStyleLightHeavy BarStyle = "light-heavy"
	// BarStyleHeavyLight is the "heavy-light" value.
	BarStyleHeavyLight BarStyle = "heavy-light"
	// BarStyleHeavyHeavy is the "heavy-heavy" value.
	BarStyleHeavyHeavy BarStyle = "heavy-heavy"
	// BarStyleTick is the "tick" value.
	BarStyleTick BarStyle = "tick"
	// BarStyleShort is the "short" value.
	BarStyleShort BarStyle = "short"
	// BarStyleNone is the "none" value.
	BarStyleNone BarStyle = "none"
)

// BeamLevel represents the "beam-level" XSD simple type.
type BeamLevel uint64

// BeamValue represents the "beam-value" XSD simple type.
type BeamValue string

const (
	// BeamValueBegin is the "begin" value.
	BeamValueBegin BeamValue = "begin"
	// BeamValueContinue is the "continue" value.
	BeamValueContinue BeamValue = "continue"
	// BeamValueEnd is the "end" value.
	BeamValueEnd BeamValue = "end"
	// BeamValueForwardHook is the "forward hook" value.
	BeamValueForwardHook BeamValue = "forward hook"
	// BeamValueBackwardHook is the "backward hook" value.
	BeamValueBackwardHook BeamValue = "backward hook"
)

// BeaterValue represents the "beater-value" XSD simple type.
type BeaterValue string

const (
	// BeaterValueBow is the "bow" value.
	BeaterValueBow BeaterValue = "bow"
	// BeaterValueChimeHammer is the "chime hammer" value.
	BeaterValueChimeHammer BeaterValue = "chime hammer"
	// BeaterValueCoin is the "coin" value.
	BeaterValueCoin BeaterValue = "coin"
	// BeaterValueDrumStick is the "drum stick" value.
	BeaterValueDrumStick BeaterValue = "drum stick"
	// BeaterValueFinger is the "finger" value.
	BeaterValueFinger BeaterValue = "finger"
	// BeaterValueFingernail is the "fingernail" value.
	BeaterValueFingernail BeaterValue = "fingernail"
	// BeaterValueFist is the "fist" value.
	BeaterValueFist BeaterValue = "fist"
	// BeaterValueGuiroScraper is the "guiro scraper" value.
	BeaterValueGuiroScraper BeaterValue = "guiro scraper"
	// BeaterValueHammer is the "hammer" value.
	BeaterValueHammer BeaterValue = "hammer"
	// BeaterValueHand is the "hand" value.
	BeaterValueHand BeaterValue = "hand"
	// BeaterValueJazzStick is the "jazz stick" value.
	BeaterValueJazzStick BeaterValue = "jazz stick"
	// BeaterValueKnittingNeedle is the "knitting needle" value.
	BeaterValueKnittingNeedle BeaterValue = "knitting needle"
	// BeaterValueMetalHammer is the "metal hammer" value.
	BeaterValueMetalHammer BeaterValue = "metal hammer"
	// BeaterValueSlideBrushOnGong is the "slide brush on gong" value.
	BeaterValueSlideBrushOnGong BeaterValue = "slide brush on gong"
	// BeaterValueSnareStick is the "snare stick" value.
	BeaterValueSnareStick BeaterValue = "snare stick"
	// BeaterValueSpoonMallet is the "spoon mallet" value.
	BeaterValueSpoonMallet BeaterValue = "spoon mallet"
	// BeaterValueSuperball is the "superball" value.
	BeaterValueSuperball BeaterValue = "superball"
	// BeaterValueTriangleBeater is the "triangle beater" value.
	BeaterValueTriangleBeater BeaterValue = "triangle beater"
	// BeaterValueTriangleBeaterPlain is the "triangle beater plain" value.
	BeaterValueTriangleBeaterPlain BeaterValue = "triangle beater plain"
	// BeaterValueWireBrush is the "wire brush" value.
	BeaterValueWireBrush BeaterValue = "wire brush"
)

// BendShape represents the "bend-shape" XSD simple type.
type BendShape string

const (
	// BendShapeAngled is the "angled" value.
	BendShapeAngled BendShape = "angled"
	// BendShapeCurved is the "curved" value.
	BendShapeCurved BendShape = "curved"
)

// BreathMarkValue represents the "breath-mark-value" XSD simple type.
type BreathMarkValue string

const (
	// BreathMarkValueEmpty is the empty value.
	BreathMarkValueEmpty BreathMarkValue = ""
	// BreathMarkValueComma is the "comma" value.
	BreathMarkValueComma BreathMarkValue = "comma"
	// BreathMarkValueTick is the "tick" value.
	BreathMarkValueTick BreathMarkValue = "tick"
	// BreathMarkValueUpbow is the "upbow" value.
	BreathMarkValueUpbow BreathMarkValue = "upbow"
	// BreathMarkValueSalzedo is the "salzedo" value.
	BreathMarkValueSalzedo BreathMarkValue = "salzedo"
)

// CaesuraValue represents the "caesura-value" XSD simple type.
type CaesuraValue string

const (
	// CaesuraValueNormal is the "normal" value.
	CaesuraValueNormal CaesuraValue = "normal"
	// CaesuraValueThick is the "thick" value.
	CaesuraValueThick CaesuraValue = "thick"
	// CaesuraValueShort is the "short" value.
	CaesuraValueShort CaesuraValue = "short"
	// CaesuraValueCurved is the "curved" value.
	CaesuraValueCurved CaesuraValue = "curved"
	// CaesuraValueSingle is the "single" value.
	CaesuraValueSingle CaesuraValue = "single"
	// CaesuraValueEmpty is the empty value.
	CaesuraValueEmpty CaesuraValue = ""
)

// CancelLocation represents the "cancel-location" XSD simple type.
type CancelLocation string

const (
	// CancelLocationLeft is the "left" value.
	CancelLocationLeft CancelLocation = "left"
	// CancelLocationRight is the "right" value.
	CancelLocationRight CancelLocation = "right"
	// CancelLocationBeforeBarline is the "before-barline" value.
	CancelLocationBeforeBarline CancelLocation = "before-barline"
)

// CircularArrow represents the "circular-arrow" XSD simple type.
type CircularArrow string

const (
	// CircularArrowClockwise is the "clockwise" value.
	CircularArrowClockwise CircularArrow = "clockwise"
	// CircularArrowAnticlockwise is the "anticlockwise" value.
	CircularArrowAnticlockwise CircularArrow = "anticlockwise"
)

// ClefSign represents the "clef-sign" XSD simple type.
type ClefSign string

const (
	// ClefSignG is the "G" value.
	ClefSignG ClefSign = "G"
	// ClefSignF is the "F" value.
	ClefSignF ClefSign = "F"
	// ClefSignC is the "C" value.
	ClefSignC ClefSign = "C"
	// ClefSignPercussion is the "percussion" value.
	ClefSignPercussion ClefSign = "percussion"
	// ClefSignTAB is the "TAB" value.
	ClefSignTAB ClefSign = "TAB"
	// ClefSignJianpu is the "jianpu" value.
	ClefSignJianpu ClefSign = "jianpu"
	// ClefSignNone is the "none" value.
	ClefSignNone ClefSign = "none"
)

// Color represents the "color" XSD simple type.
type Color string

// CommaSeparatedText represents the "comma-separated-text" XSD simple type.
type CommaSeparatedText string

// CSSFontSize represents the "css-font-size" XSD simple type.
type CSSFontSize string

const (
	// CSSFontSizeXxSmall is the "xx-small" value.
	CSSFontSizeXxSmall CSSFontSize = "xx-small"
	// CSSFontSizeXSmall is the "x-small" value.
	CSSFontSizeXSmall CSSFontSize = "x-small"
	// CSSFontSizeSmall is the "small" value.
	CSSFontSizeSmall CSSFontSize = "small"
	// CSSFontSizeMedium is the "medium" value.
	CSSFontSizeMedium CSSFontSize = "medium"
	// CSSFontSizeLarge is the "large" value.
	CSSFontSizeLarge CSSFontSize = "large"
	// CSSFontSizeXLarge is the "x-large" value.
	CSSFontSizeXLarge CSSFontSize = "x-large"
	// CSSFontSizeXxLarge is the "xx-large" value.
	CSSFontSizeXxLarge CSSFontSize = "xx-large"
)

// DegreeSymbolValue represents the "degree-symbol-value" XSD simple type.
type DegreeSymbolValue string

const (
	// DegreeSymbolValueMajor is the "major" value.
	DegreeSymbolValueMajor DegreeSymbolValue = "major"
	// DegreeSymbolValueMinor is the "minor" value.
	DegreeSymbolValueMinor DegreeSymbolValue = "minor"
	// DegreeSymbolValueAugmented is the "augmented" value.
	DegreeSymbolValueAugmented DegreeSymbolValue = "augmented"
	// DegreeSymbolValueDiminished is the "diminished" value.
	DegreeSymbolValueDiminished DegreeSymbolValue = "diminished"
	// DegreeSymbolValueHalfDiminished is the "half-diminished" value.
	DegreeSymbolValueHalfDiminished DegreeSymbolValue = "half-diminished"
)

// DegreeTypeValue represents the "degree-type-value" XSD simple type.
type DegreeTypeValue string

const (
	// DegreeTypeValueAdd is the "add" value.
	DegreeTypeValueAdd DegreeTypeValue = "add"
	// DegreeTypeValueAlter is the "alter" value.
	DegreeTypeValueAlter DegreeTypeValue = "alter"
	// DegreeTypeValueSubtract is the "subtract" value.
	DegreeTypeValueSubtract DegreeTypeValue = "subtract"
)

// DistanceType represents the "distance-type" XSD simple type.
type DistanceType string

// Divisions represents the "divisions" XSD simple type.
type Divisions float64

// EffectValue represents the "effect-value" XSD simple type.
type EffectValue string

const (
	// EffectValueAnvil is the "anvil" value.
	EffectValueAnvil EffectValue = "anvil"
	// EffectValueAutoHorn is the "auto horn" value.
	EffectValueAutoHorn EffectValue = "auto horn"
	// EffectValueBirdWhistle is the "bird whistle" value.
	EffectValueBirdWhistle EffectValue = "bird whistle"
	// EffectValueCannon is the "cannon" value.
	EffectValueCannon EffectValue = "cannon"
	// EffectValueDuckCall is the "duck call" value.
	EffectValueDuckCall EffectValue = "duck call"
	// EffectValueGunShot is the "gun shot" value.
	EffectValueGunShot EffectValue = "gun shot"
	// EffectValueKlaxonHorn is the "klaxon horn" value.
	EffectValueKlaxonHorn EffectValue = "klaxon horn"
	// EffectValueLionsRoar is the "lions roar" value.
	EffectValueLionsRoar EffectValue = "lions roar"
	// EffectValueLotusFlute is the "lotus flute" value.
	EffectValueLotusFlute EffectValue = "lotus flute"
	// EffectValueMegaphone is the "megaphone" value.
	EffectValueMegaphone EffectValue = "megaphone"
	// EffectValuePoliceWhistle is the "police whistle" value.
	EffectValuePoliceWhistle EffectValue = "police whistle"
	// EffectValueSiren is the "siren" value.
	EffectValueSiren EffectValue = "siren"
	// EffectValueSlideWhistle is the "slide whistle" value.
	EffectValueSlideWhistle EffectValue = "slide whistle"
	// EffectValueThunderSheet is the "thunder sheet" value.
	EffectValueThunderSheet EffectValue = "thunder sheet"
	// EffectValueWindMachine is the "wind machine" value.
	EffectValueWindMachine EffectValue = "wind machine"
	// EffectValueWindWhistle is the "wind whistle" value.
	EffectValueWindWhistle EffectValue = "wind whistle"
)

// EnclosureShape represents the "enclosure-shape" XSD simple type.
type EnclosureShape string

const (
	// EnclosureShapeRectangle is the "rectangle" value.
	EnclosureShapeRectangle EnclosureShape = "rectangle"
	// EnclosureShapeSquare is the "square" value.
	EnclosureShapeSquare EnclosureShape = "square"
	// EnclosureShapeOval is the "oval" value.
	EnclosureShapeOval EnclosureShape = "oval"
	// EnclosureShapeCircle is the "circle" value.
	EnclosureShapeCircle EnclosureShape = "circle"
	// EnclosureShapeBracket is the "bracket" value.
	EnclosureShapeBracket EnclosureShape = "bracket"
	// EnclosureShapeInvertedBracket is the "inverted-bracket" value.
	EnclosureShapeInvertedBracket EnclosureShape = "inverted-bracket"
	// EnclosureShapeTriangle is the "triangle" value.
	EnclosureShapeTriangle EnclosureShape = "triangle"
	// EnclosureShapeDiamond is the "diamond" value.
	EnclosureShapeDiamond EnclosureShape = "diamond"
	// EnclosureShapePentagon is the "pentagon" value.
	EnclosureShapePentagon EnclosureShape = "pentagon"
	// EnclosureShapeHexagon is the "hexagon" value.
	EnclosureShapeHexagon EnclosureShape = "hexagon"
	// EnclosureShapeHeptagon is the "heptagon" value.
	EnclosureShapeHeptagon EnclosureShape = "heptagon"
	// EnclosureShapeOctagon is the "octagon" value.
	EnclosureShapeOctagon EnclosureShape = "octagon"
	// EnclosureShapeNonagon is the "nonagon" value.
	EnclosureShapeNonagon EnclosureShape = "nonagon"
	// EnclosureShapeDecagon is the "decagon" value.
	EnclosureShapeDecagon EnclosureShape = "decagon"
	// EnclosureShapeNone is the "none" value.
	EnclosureShapeNone EnclosureShape = "none"
)

// EndingNumber represents the "ending-number" XSD simple type.
type EndingNumber string

// Fan represents the "fan" XSD simple type.
type Fan string

const (
	// FanAccel is the "accel" value.
	FanAccel Fan = "accel"
	// FanRit is the "rit" value.
	FanRit Fan = "rit"
	// FanNone is the "none" value.
	FanNone Fan = "none"
)

// FermataShape represents the "fermata-shape" XSD simple type.
type FermataShape string

const (
	// FermataShapeNormal is the "normal" value.
	FermataShapeNormal FermataShape = "normal"
	// FermataShapeAngled is the "angled" value.
	FermataShapeAngled FermataShape = "angled"
	// FermataShapeSquare is the "square" value.
	FermataShapeSquare FermataShape = "square"
	// FermataShapeDoubleAngled is the "double-angled" value.
	FermataShapeDoubleAngled FermataShape = "double-angled"
	// FermataShapeDoubleSquare is the "double-square" value.
	FermataShapeDoubleSquare FermataShape = "double-square"
	// FermataShapeDoubleDot is the "double-dot" value.
	FermataShapeDoubleDot FermataShape = "double-dot"
	// FermataShapeHalfCurve is the "half-curve" value.
	FermataShapeHalfCurve FermataShape = "half-curve"
	// FermataShapeCurlew is the "curlew" value.
	FermataShapeCurlew FermataShape = "curlew"
	// FermataShapeEmpty is the empty value.
	FermataShapeEmpty FermataShape = ""
)

// Fifths represents the "fifths" XSD simple type.
type Fifths int64

// FontFamily represents the "font-family" XSD simple type.
type FontFamily CommaSeparatedText

// FontSize represents the "font-size" XSD simple type.
type FontSize string

// FontStyle represents the "font-style" XSD simple type.
type FontStyle string

const (
	// FontStyleNormal is the "normal" value.
	FontStyleNormal FontStyle = "normal"
	// FontStyleItalic is the "italic" value.
	FontStyleItalic FontStyle = "italic"
)

// FontWeight represents the "font-weight" XSD simple type.
type FontWeight string

const (
	// FontWeightNormal is the "normal" value.
	FontWeightNormal FontWeight = "normal"
	// FontWeightBold is the "bold" value.
	FontWeightBold FontWeight = "bold"
)

// GlassValue represents the "glass-value" XSD simple type.
type GlassValue string

const (
	// GlassValueGlassHarmonica is the "glass harmonica" value.
	GlassValueGlassHarmonica GlassValue = "glass harmonica"
	// GlassValueGlassHarp is the "glass harp" value.
	GlassValueGlassHarp GlassValue = "glass harp"
	// GlassValueWindChimes is the "wind chimes" value.
	GlassValueWindChimes GlassValue = "wind chimes"
)

// GlyphType represents the "glyph-type" XSD simple type.
type GlyphType string

// GroupBarlineValue represents the "group-barline-value" XSD simple type.
type GroupBarlineValue string

const (
	// GroupBarlineValueYes is the "yes" value.
	GroupBarlineValueYes GroupBarlineValue = "yes"
	// GroupBarlineValueNo is the "no" value.
	GroupBarlineValueNo GroupBarlineValue = "no"
	// GroupBarlineValueMensurstrich is the "Mensurstrich" value.
	GroupBarlineValueMensurstrich GroupBarlineValue = "Mensurstrich"
)

// GroupSymbolValue represents the "group-symbol-value" XSD simple type.
type GroupSymbolValue string

const (
	// GroupSymbolValueNone is the "none" value.
	GroupSymbolValueNone GroupSymbolValue = "none"
	// GroupSymbolValueBrace is the "brace" value.
	GroupSymbolValueBrace GroupSymbolValue = "brace"
	// GroupSymbolValueLine is the "line" value.
	GroupSymbolValueLine GroupSymbolValue = "line"
	// GroupSymbolValueBracket is the "bracket" value.
	GroupSymbolValueBracket GroupSymbolValue = "bracket"
	// GroupSymbolValueSquare is the "square" value.
	GroupSymbolValueSquare GroupSymbolValue = "square"
)

// HandbellValue represents the "handbell-value" XSD simple type.
type HandbellValue string

const (
	// HandbellValueBelltree is the "belltree" value.
	HandbellValueBelltree HandbellValue = "belltree"
	// HandbellValueDamp is the "damp" value.
	HandbellValueDamp HandbellValue = "damp"
	// HandbellValueEcho is the "echo" value.
	HandbellValueEcho HandbellValue = "echo"
	// HandbellValueGyro is the "gyro" value.
	HandbellValueGyro HandbellValue = "gyro"
	// HandbellValueHandMartellato is the "hand martellato" value.
	HandbellValueHandMartellato HandbellValue = "hand martellato"
	// HandbellValueMalletLift is the "mallet lift" value.
	HandbellValueMalletLift HandbellValue = "mallet lift"
	// HandbellValueMalletTable is the "mallet table" value.
	HandbellValueMalletTable HandbellValue = "mallet table"
	// HandbellValueMartellato is the "martellato" value.
	HandbellValueMartellato HandbellValue = "martellato"
	// HandbellValueMartellatoLift is the "martellato lift" value.
	HandbellValueMartellatoLift HandbellValue = "martellato lift"
	// HandbellValueMutedMartellato is the "muted martellato" value.
	HandbellValueMutedMartellato HandbellValue = "muted martellato"
	// HandbellValuePluckLift is the "pluck lift" value.
	HandbellValuePluckLift HandbellValue = "pluck lift"
	// HandbellValueSwing is the "swing" value.
	HandbellValueSwing HandbellValue = "swing"
)

// HarmonClosedLocation represents the "harmon-closed-location" XSD simple type.
type HarmonClosedLocation string

const (
	// HarmonClosedLocationRight is the "right" value.
	HarmonClosedLocationRight HarmonClosedLocation = "right"
	// HarmonClosedLocationBottom is the "bottom" value.
	HarmonClosedLocationBottom HarmonClosedLocation = "bottom"
	// HarmonClosedLocationLeft is the "left" value.
	HarmonClosedLocationLeft HarmonClosedLocation = "left"
	// HarmonClosedLocationTop is the "top" value.
	HarmonClosedLocationTop HarmonClosedLocation = "top"
)

// HarmonClosedValue represents the "harmon-closed-value" XSD simple type.
type HarmonClosedValue string

const (
	// HarmonClosedValueYes is the "yes" value.
	HarmonClosedValueYes HarmonClosedValue = "yes"
	// HarmonClosedValueNo is the "no" value.
	HarmonClosedValueNo HarmonClosedValue = "no"
	// HarmonClosedValueHalf is the "half" value.
	HarmonClosedValueHalf HarmonClosedValue = "half"
)

// HarmonyArrangement represents the "harmony-arrangement" XSD simple type.
type HarmonyArrangement string

const (
	// HarmonyArrangementVertical is the "vertical" value.
	HarmonyArrangementVertical HarmonyArrangement = "vertical"
	// HarmonyArrangementHorizontal is the "horizontal" value.
	HarmonyArrangementHorizontal HarmonyArrangement = "horizontal"
	// HarmonyArrangementDiagonal is the "diagonal" value.
	HarmonyArrangementDiagonal HarmonyArrangement = "diagonal"
)

// HarmonyType represents the "harmony-type" XSD simple type.
type HarmonyType string

const (
	// HarmonyTypeExplicit is the "explicit" value.
	HarmonyTypeExplicit HarmonyType = "explicit"
	// HarmonyTypeImplied is the "implied" value.
	HarmonyTypeImplied HarmonyType = "implied"
	// HarmonyTypeAlternate is the "alternate" value.
	HarmonyTypeAlternate HarmonyType = "alternate"
)

// HoleClosedLocation represents the "hole-closed-location" XSD simple type.
type HoleClosedLocation string

const (
	// HoleClosedLocationRight is the "right" value.
	HoleClosedLocationRight HoleClosedLocation = "right"
	// HoleClosedLocationBottom is the "bottom" value.
	HoleClosedLocationBottom HoleClosedLocation = "bottom"
	// HoleClosedLocationLeft is the "left" value.
	HoleClosedLocationLeft HoleClosedLocation = "left"
	// HoleClosedLocationTop is the "top" value.
	HoleClosedLocationTop HoleClosedLocation = "top"
)

// HoleClosedValue represents the "hole-closed-value" XSD simple type.
type HoleClosedValue string

const (
	// HoleClosedValueYes is the "yes" value.
	HoleClosedValueYes HoleClosedValue = "yes"
	// HoleClosedValueNo is the "no" value.
	HoleClosedValueNo HoleClosedValue = "no"
	// HoleClosedValueHalf is the "half" value.
	HoleClosedValueHalf HoleClosedValue = "half"
)

// KindValue represents the "kind-value" XSD simple type.
type KindValue string

const (
	// KindValueMajor is the "major" value.
	KindValueMajor KindValue = "major"
	// KindValueMinor is the "minor" value.
	KindValueMinor KindValue = "minor"
	// KindValueAugmented is the "augmented" value.
	KindValueAugmented KindValue = "augmented"
	// KindValueDiminished is the "diminished" value.
	KindValueDiminished KindValue = "diminished"
	// KindValueDominant is the "dominant" value.
	KindValueDominant KindValue = "dominant"
	// KindValueMajorSeventh is the "major-seventh" value.
	KindValueMajorSeventh KindValue = "major-seventh"
	// KindValueMinorSeventh is the "minor-seventh" value.
	KindValueMinorSeventh KindValue = "minor-seventh"
	// KindValueDiminishedSeventh is the "diminished-seventh" value.
	KindValueDiminishedSeventh KindValue = "diminished-seventh"
	// KindValueAugmentedSeventh is the "augmented-seventh" value.
	KindValueAugmentedSeventh KindValue = "augmented-seventh"
	// KindValueHalfDiminished is the "half-diminished" value.
	KindValueHalfDiminished KindValue = "half-diminished"
	// KindValueMajorMinor is the "major-minor" value.
	KindValueMajorMinor KindValue = "major-minor"
	// KindValueMajorSixth is the "major-sixth" value.
	KindValueMajorSixth KindValue = "major-sixth"
	// KindValueMinorSixth is the "minor-sixth" value.
	KindValueMinorSixth KindValue = "minor-sixth"
	// KindValueDominantNinth is the "dominant-ninth" value.
	KindValueDominantNinth KindValue = "dominant-ninth"
	// KindValueMajorNinth is the "major-ninth" value.
	KindValueMajorNinth KindValue = "major-ninth"
	// KindValueMinorNinth is the "minor-ninth" value.
	KindValueMinorNinth KindValue = "minor-ninth"
	// KindValueDominant11th is the "dominant-11th" value.
	KindValueDominant11th KindValue = "dominant-11th"
	// KindValueMajor11th is the "major-11th" value.
	KindValueMajor11th KindValue = "major-11th"
	// KindValueMinor11th is the "minor-11th" value.
	KindValueMinor11th KindValue = "minor-11th"
	// KindValueDominant13th is the "dominant-13th" value.
	KindValueDominant13th KindValue = "dominant-13th"
	// KindValueMajor13th is the "major-13th" value.
	KindValueMajor13th KindValue = "major-13th"
	// KindValueMinor13th is the "minor-13th" value.
	KindValueMinor13th KindValue = "minor-13th"
	// KindValueSuspendedSecond is the "suspended-second" value.
	KindValueSuspendedSecond KindValue = "suspended-second"
	// KindValueSuspendedFourth is the "suspended-fourth" value.
	KindValueSuspendedFourth KindValue = "suspended-fourth"
	// KindValueNeapolitan is the "Neapolitan" value.
	KindValueNeapolitan KindValue = "Neapolitan"
	// KindValueItalian is the "Italian" value.
	KindValueItalian KindValue = "Italian"
	// KindValueFrench is the "French" value.
	KindValueFrench KindValue = "French"
	// KindValueGerman is the "German" value.
	KindValueGerman KindValue = "German"
	// KindValuePedal is the "pedal" value.
	KindValuePedal KindValue = "pedal"
	// KindValuePower is the "power" value.
	KindValuePower KindValue = "power"
	// KindValueTristan is the "Tristan" value.
	KindValueTristan KindValue = "Tristan"
	// KindValueOther is the "other" value.
	KindValueOther KindValue = "other"
	// KindValueNone is the "none" value.
	KindValueNone KindValue = "none"
)

// LeftCenterRight represents the "left-center-right" XSD simple type.
type LeftCenterRight string

const (
	// LeftCenterRightLeft is the "left" value.
	LeftCenterRightLeft LeftCenterRight = "left"
	// LeftCenterRightCenter is the "center" value.
	LeftCenterRightCenter LeftCenterRight = "center"
	// LeftCenterRightRight is the "right" value.
	LeftCenterRightRight LeftCenterRight = "right"
)

// LeftRight represents the "left-right" XSD simple type.
type LeftRight string

const (
	// LeftRightLeft is the "left" value.
	LeftRightLeft LeftRight = "left"
	// LeftRightRight is the "right" value.
	LeftRightRight LeftRight = "right"
)

// LineEnd represents the "line-end" XSD simple type.
type LineEnd string

const (
	// LineEndUp is the "up" value.
	LineEndUp LineEnd = "up"
	// LineEndDown is the "down" value.
	LineEndDown LineEnd = "down"
	// LineEndBoth is the "both" value.
	LineEndBoth LineEnd = "both"
	// LineEndArrow is the "arrow" value.
	LineEndArrow LineEnd = "arrow"
	// LineEndNone is the "none" value.
	LineEndNone LineEnd = "none"
)

// LineLength represents the "line-length" XSD simple type.
type LineLength string

const (
	// LineLengthShort is the "short" value.
	LineLengthShort LineLength = "short"
	// LineLengthMedium is the "medium" value.
	LineLengthMedium LineLength = "medium"
	// LineLengthLong is the "long" value.
	LineLengthLong LineLength = "long"
)

// LineShape represents the "line-shape" XSD simple type.
type LineShape string

const (
	// LineShapeStraight is the "straight" value.
	LineShapeStraight LineShape = "straight"
	// LineShapeCurved is the "curved" value.
	LineShapeCurved LineShape = "curved"
)

// LineType represents the "line-type" XSD simple type.
type LineType string

const (
	// LineTypeSolid is the "solid" value.
	LineTypeSolid LineType = "solid"
	// LineTypeDashed is the "dashed" value.
	LineTypeDashed LineType = "dashed"
	// LineTypeDotted is the "dotted" value.
	LineTypeDotted LineType = "dotted"
	// LineTypeWavy is the "wavy" value.
	LineTypeWavy LineType = "wavy"
)

// LineWidthType represents the "line-width-type" XSD simple type.
type LineWidthType string

// MarginType represents the "margin-type" XSD simple type.
type MarginType string

const (
	// MarginTypeOdd is the "odd" value.
	MarginTypeOdd MarginType = "odd"
	// MarginTypeEven is the "even" value.
	MarginTypeEven MarginType = "even"
	// MarginTypeBoth is the "both" value.
	MarginTypeBoth MarginType = "both"
)

// MeasureNumberingValue represents the "measure-numbering-value" XSD simple type.
type MeasureNumberingValue string

const (
	// MeasureNumberingValueNone is the "none" value.
	MeasureNumberingValueNone MeasureNumberingValue = "none"
	// MeasureNumberingValueMeasure is the "measure" value.
	MeasureNumberingValueMeasure MeasureNumberingValue = "measure"
	// MeasureNumberingValueSystem is the "system" value.
	MeasureNumberingValueSystem MeasureNumberingValue = "system"
)

// MeasureText represents the "measure-text" XSD simple type.
type MeasureText string

// MembraneValue represents the "membrane-value" XSD simple type.
type MembraneValue string

const (
	// MembraneValueBassDrum is the "bass drum" value.
	MembraneValueBassDrum MembraneValue = "bass drum"
	// MembraneValueBassDrumOnSide is the "bass drum on side" value.
	MembraneValueBassDrumOnSide MembraneValue = "bass drum on side"
	// MembraneValueBongos is the "bongos" value.
	MembraneValueBongos MembraneValue = "bongos"
	// MembraneValueChineseTomtom is the "Chinese tomtom" value.
	MembraneValueChineseTomtom MembraneValue = "Chinese tomtom"
	// MembraneValueCongaDrum is the "conga drum" value.
	MembraneValueCongaDrum MembraneValue = "conga drum"
	// MembraneValueCuica is the "cuica" value.
	MembraneValueCuica MembraneValue = "cuica"
	// MembraneValueGobletDrum is the "goblet drum" value.
	MembraneValueGobletDrum MembraneValue = "goblet drum"
	// MembraneValueIndoAmericanTomtom is the "Indo-American tomtom" value.
	MembraneValueIndoAmericanTomtom MembraneValue = "Indo-American tomtom"
	// MembraneValueJapaneseTomtom is the "Japanese tomtom" value.
	MembraneValueJapaneseTomtom MembraneValue = "Japanese tomtom"
	// MembraneValueMilitaryDrum is the "military drum" value.
	MembraneValueMilitaryDrum MembraneValue = "military drum"
	// MembraneValueSnareDrum is the "snare drum" value.
	MembraneValueSnareDrum MembraneValue = "snare drum"
	// MembraneValueSnareDrumSnaresOff is the "snare drum snares off" value.
	MembraneValueSnareDrumSnaresOff MembraneValue = "snare drum snares off"
	// MembraneValueTabla is the "tabla" value.
	MembraneValueTabla MembraneValue = "tabla"
	// MembraneValueTambourine is the "tambourine" value.
	MembraneValueTambourine MembraneValue = "tambourine"
	// MembraneValueTenorDrum is the "tenor drum" value.
	MembraneValueTenorDrum MembraneValue = "tenor drum"
	// MembraneValueTimbales is the "timbales" value.
	MembraneValueTimbales MembraneValue = "timbales"
	// MembraneValueTomtom is the "tomtom" value.
	MembraneValueTomtom MembraneValue = "tomtom"
)

// MetalValue represents the "metal-value" XSD simple type.
type MetalValue string

const (
	// MetalValueAgogo is the "agogo" value.
	MetalValueAgogo MetalValue = "agogo"
	// MetalValueAlmglocken is the "almglocken" value.
	MetalValueAlmglocken MetalValue = "almglocken"
	// MetalValueBell is the "bell" value.
	MetalValueBell MetalValue = "bell"
	// MetalValueBellPlate is the "bell plate" value.
	MetalValueBellPlate MetalValue = "bell plate"
	// MetalValueBellTree is the "bell tree" value.
	MetalValueBellTree MetalValue = "bell tree"
	// MetalValueBrakeDrum is the "brake drum" value.
	MetalValueBrakeDrum MetalValue = "brake drum"
	// MetalValueCencerro is the "cencerro" value.
	MetalValueCencerro MetalValue = "cencerro"
	// MetalValueChainRattle is the "chain rattle" value.
	MetalValueChainRattle MetalValue = "chain rattle"
	// MetalValueChineseCymbal is the "Chinese cymbal" value.
	MetalValueChineseCymbal MetalValue = "Chinese cymbal"
	// MetalValueCowbell is the "cowbell" value.
	MetalValueCowbell MetalValue = "cowbell"
	// MetalValueCrashCymbals is the "crash cymbals" value.
	MetalValueCrashCymbals MetalValue = "crash cymbals"
	// MetalValueCrotale is the "crotale" value.
	MetalValueCrotale MetalValue = "crotale"
	// MetalValueCymbalTongs is the "cymbal tongs" value.
	MetalValueCymbalTongs MetalValue = "cymbal tongs"
	// MetalValueDomedGong is the "domed gong" value.
	MetalValueDomedGong MetalValue = "domed gong"
	// MetalValueFingerCymbals is the "finger cymbals" value.
	MetalValueFingerCymbals MetalValue = "finger cymbals"
	// MetalValueFlexatone is the "flexatone" value.
	MetalValueFlexatone MetalValue = "flexatone"
	// MetalValueGong is the "gong" value.
	MetalValueGong MetalValue = "gong"
	// MetalValueHiHat is the "hi-hat" value.
	MetalValueHiHat MetalValue = "hi-hat"
	// MetalValueHighHatCymbals is the "high-hat cymbals" value.
	MetalValueHighHatCymbals MetalValue = "high-hat cymbals"
	// MetalValueHandbell is the "handbell" value.
	MetalValueHandbell MetalValue = "handbell"
	// MetalValueJawHarp is the "jaw harp" value.
	MetalValueJawHarp MetalValue = "jaw harp"
	// MetalValueJingleBells is the "jingle bells" value.
	MetalValueJingleBells MetalValue = "jingle bells"
	// MetalValueMusicalSaw is the "musical saw" value.
	MetalValueMusicalSaw MetalValue = "musical saw"
	// MetalValueShellBells is the "shell bells" value.
	MetalValueShellBells MetalValue = "shell bells"
	// MetalValueSistrum is the "sistrum" value.
	MetalValueSistrum MetalValue = "sistrum"
	// MetalValueSizzleCymbal is the "sizzle cymbal" value.
	MetalValueSizzleCymbal MetalValue = "sizzle cymbal"
	// MetalValueSleighBells is the "sleigh bells" value.
	MetalValueSleighBells MetalValue = "sleigh bells"
	// MetalValueSuspendedCymbal is the "suspended cymbal" value.
	MetalValueSuspendedCymbal MetalValue = "suspended cymbal"
	// MetalValueTamTam is the "tam tam" value.
	MetalValueTamTam MetalValue = "tam tam"
	// MetalValueTamTamWithBeater is the "tam tam with beater" value.
	MetalValueTamTamWithBeater MetalValue = "tam tam with beater"
	// MetalValueTriangle is the "triangle" value.
	MetalValueTriangle MetalValue = "triangle"
	// MetalValueVietnameseHat is the "Vietnamese hat" value.
	MetalValueVietnameseHat MetalValue = "Vietnamese hat"
)

// MIDI128 represents the "midi-128" XSD simple type.
type MIDI128 uint64

// MIDI16 represents the "midi-16" XSD simple type.
type MIDI16 uint64

// MIDI16384 represents the "midi-16384" XSD simple type.
type MIDI16384 uint64

// Millimeters represents the "millimeters" XSD simple type.
type Millimeters float64

// Milliseconds represents the "milliseconds" XSD simple type.
type Milliseconds uint64

// Mode represents the "mode" XSD simple type.
type Mode string

// Mute represents the "mute" XSD simple type.
type Mute string

const (
	// MuteOn is the "on" value.
	MuteOn Mute = "on"
	// MuteOff is the "off" value.
	MuteOff Mute = "off"
	// MuteStraight is the "straight" value.
	MuteStraight Mute = "straight"
	// MuteCup is the "cup" value.
	MuteCup Mute = "cup"
	// MuteHarmonNoStem is the "harmon-no-stem" value.
	MuteHarmonNoStem Mute = "harmon-no-stem"
	// MuteHarmonStem is the "harmon-stem" value.
	MuteHarmonStem Mute = "harmon-stem"
	// MuteBucket is the "bucket" value.
	MuteBucket Mute = "bucket"
	// MutePlunger is the "plunger" value.
	MutePlunger Mute = "plunger"
	// MuteHat is the "hat" value.
	MuteHat Mute = "hat"
	// MuteSolotone is the "solotone" value.
	MuteSolotone Mute = "solotone"
	// MutePractice is the "practice" value.
	MutePractice Mute = "practice"
	// MuteStopMute is the "stop-mute" value.
	MuteStopMute Mute = "stop-mute"
	// MuteStopHand is the "stop-hand" value.
	MuteStopHand Mute = "stop-hand"
	// MuteEcho is the "echo" value.
	MuteEcho Mute = "echo"
	// MutePalm is the "palm" value.
	MutePalm Mute = "palm"
)

// NonNegativeDecimal represents the "non-negative-decimal" XSD simple type.
type NonNegativeDecimal float64

// NoteSizeType represents the "note-size-type" XSD simple type.
type NoteSizeType string

const (
	// NoteSizeTypeCue is the "cue" value.
	NoteSizeTypeCue NoteSizeType = "cue"
	// NoteSizeTypeGrace is the "grace" value.
	NoteSizeTypeGrace NoteSizeType = "grace"
	// NoteSizeTypeGraceCue is the "grace-cue" value.
	NoteSizeTypeGraceCue NoteSizeType = "grace-cue"
	// NoteSizeTypeLarge is the "large" value.
	NoteSizeTypeLarge NoteSizeType = "large"
)

// NoteTypeValue represents the "note-type-value" XSD simple type.
type NoteTypeValue string

const (
	// NoteTypeValue1024th is the "1024th" value.
	NoteTypeValue1024th NoteTypeValue = "1024th"
	// NoteTypeValue512th is the "512th" value.
	NoteTypeValue512th NoteTypeValue = "512th"
	// NoteTypeValue256th is the "256th" value.
	NoteTypeValue256th NoteTypeValue = "256th"
	// NoteTypeValue128th is the "128th" value.
	NoteTypeValue128th NoteTypeValue = "128th"
	// NoteTypeValue64th is the "64th" value.
	NoteTypeValue64th NoteTypeValue = "64th"
	// NoteTypeValue32nd is the "32nd" value.
	NoteTypeValue32nd NoteTypeValue = "32nd"
	// NoteTypeValue16th is the "16th" value.
	NoteTypeValue16th NoteTypeValue = "16th"
	// NoteTypeValueEighth is the "eighth" value.
	NoteTypeValueEighth NoteTypeValue = "eighth"
	// NoteTypeValueQuarter is the "quarter" value.
	NoteTypeValueQuarter NoteTypeValue = "quarter"
	// NoteTypeValueHalf is the "half" value.
	NoteTypeValueHalf NoteTypeValue = "half"
	// NoteTypeValueWhole is the "whole" value.
	NoteTypeValueWhole NoteTypeValue = "whole"
	// NoteTypeValueBreve is the "breve" value.
	NoteTypeValueBreve NoteTypeValue = "breve"
	// NoteTypeValueLong is the "long" value.
	NoteTypeValueLong NoteTypeValue = "long"
	// NoteTypeValueMaxima is the "maxima" value.
	NoteTypeValueMaxima NoteTypeValue = "maxima"
)

// NoteheadValue represents the "notehead-value" XSD simple type.
type NoteheadValue string

const (
	// NoteheadValueSlash is the "slash" value.
	NoteheadValueSlash NoteheadValue = "slash"
	// NoteheadValueTriangle is the "triangle" value.
	NoteheadValueTriangle NoteheadValue = "triangle"
	// NoteheadValueDiamond is the "diamond" value.
	NoteheadValueDiamond NoteheadValue = "diamond"
	// NoteheadValueSquare is the "square" value.
	NoteheadValueSquare NoteheadValue = "square"
	// NoteheadValueCross is the "cross" value.
	NoteheadValueCross NoteheadValue = "cross"
	// NoteheadValueX is the "x" value.
	NoteheadValueX NoteheadValue = "x"
	// NoteheadValueCircleX is the "circle-x" value.
	NoteheadValueCircleX NoteheadValue = "circle-x"
	// NoteheadValueInvertedTriangle is the "inverted triangle" value.
	NoteheadValueInvertedTriangle NoteheadValue = "inverted triangle"
	// NoteheadValueArrowDown is the "arrow down" value.
	NoteheadValueArrowDown NoteheadValue = "arrow down"
	// NoteheadValueArrowUp is the "arrow up" value.
	NoteheadValueArrowUp NoteheadValue = "arrow up"
	// NoteheadValueCircled is the "circled" value.
	NoteheadValueCircled NoteheadValue = "circled"
	// NoteheadValueSlashed is the "slashed" value.
	NoteheadValueSlashed NoteheadValue = "slashed"
	// NoteheadValueBackSlashed is the "back slashed" value.
	NoteheadValueBackSlashed NoteheadValue = "back slashed"
	// NoteheadValueNormal is the "normal" value.
	NoteheadValueNormal NoteheadValue = "normal"
	// NoteheadValueCluster is the "cluster" value.
	NoteheadValueCluster NoteheadValue = "cluster"
	// NoteheadValueCircleDot is the "circle dot" value.
	NoteheadValueCircleDot NoteheadValue = "circle dot"
	// NoteheadValueLeftTriangle is the "left triangle" value.
	NoteheadValueLeftTriangle NoteheadValue = "left triangle"
	// NoteheadValueRectangle is the "rectangle" value.
	NoteheadValueRectangle NoteheadValue = "rectangle"
	// NoteheadValueNone is the "none" value.
	NoteheadValueNone NoteheadValue = "none"
	// NoteheadValueDo is the "do" value.
	NoteheadValueDo NoteheadValue = "do"
	// NoteheadValueRe is the "re" value.
	NoteheadValueRe NoteheadValue = "re"
	// NoteheadValueMi is the "mi" value.
	NoteheadValueMi NoteheadValue = "mi"
	// NoteheadValueFa is the "fa" value.
	NoteheadValueFa NoteheadValue = "fa"
	// NoteheadValueFaUp is the "fa up" value.
	NoteheadValueFaUp NoteheadValue = "fa up"
	// NoteheadValueSo is the "so" value.
	NoteheadValueSo NoteheadValue = "so"
	// NoteheadValueLa is the "la" value.
	NoteheadValueLa NoteheadValue = "la"
	// NoteheadValueTi is the "ti" value.
	NoteheadValueTi NoteheadValue = "ti"
	// NoteheadValueOther is the "other" value.
	NoteheadValueOther NoteheadValue = "other"
)

// NumberLevel represents the "number-level" XSD simple type.
type NumberLevel uint64

// NumberOfLines represents the "number-of-lines" XSD simple type.
type NumberOfLines uint64

// NumberOrNormal represents the "number-or-normal" XSD simple type.
type NumberOrNormal string

const (
	// NumberOrNormalNormal is the "normal" value.
	NumberOrNormalNormal NumberOrNormal = "normal"
)

// NumeralMode represents the "numeral-mode" XSD simple type.
type NumeralMode string

const (
	// NumeralModeMajor is the "major" value.
	NumeralModeMajor NumeralMode = "major"
	// NumeralModeMinor is the "minor" value.
	NumeralModeMinor NumeralMode = "minor"
	// NumeralModeNaturalMinor is the "natural minor" value.
	NumeralModeNaturalMinor NumeralMode = "natural minor"
	// NumeralModeMelodicMinor is the "melodic minor" value.
	NumeralModeMelodicMinor NumeralMode = "melodic minor"
	// NumeralModeHarmonicMinor is the "harmonic minor" value.
	NumeralModeHarmonicMinor NumeralMode = "harmonic minor"
)

// NumeralValue represents the "numeral-value" XSD simple type.
type NumeralValue uint64

// Octave represents the "octave" XSD simple type.
type Octave int64

// OnOff represents the "on-off" XSD simple type.
type OnOff string

const (
	// OnOffOn is the "on" value.
	OnOffOn OnOff = "on"
	// OnOffOff is the "off" value.
	OnOffOff OnOff = "off"
)

// OverUnder represents the "over-under" XSD simple type.
type OverUnder string

const (
	// OverUnderOver is the "over" value.
	OverUnderOver OverUnder = "over"
	// OverUnderUnder is the "under" value.
	OverUnderUnder OverUnder = "under"
)

// PedalType represents the "pedal-type" XSD simple type.
type PedalType string

const (
	// PedalTypeStart is the "start" value.
	PedalTypeStart PedalType = "start"
	// PedalTypeStop is the "stop" value.
	PedalTypeStop PedalType = "stop"
	// PedalTypeSostenuto is the "sostenuto" value.
	PedalTypeSostenuto PedalType = "sostenuto"
	// PedalTypeChange is the "change" value.
	PedalTypeChange PedalType = "change"
	// PedalTypeContinue is the "continue" value.
	PedalTypeContinue PedalType = "continue"
	// PedalTypeDiscontinue is the "discontinue" value.
	PedalTypeDiscontinue PedalType = "discontinue"
	// PedalTypeResume is the "resume" value.
	PedalTypeResume PedalType = "resume"
)

// Percent represents the "percent" XSD simple type.
type Percent float64

// PitchedValue represents the "pitched-value" XSD simple type.
type PitchedValue string

const (
	// PitchedValueCelesta is the "celesta" value.
	PitchedValueCelesta PitchedValue = "celesta"
	// PitchedValueChimes is the "chimes" value.
	PitchedValueChimes PitchedValue = "chimes"
	// PitchedValueGlockenspiel is the "glockenspiel" value.
	PitchedValueGlockenspiel PitchedValue = "glockenspiel"
	// PitchedValueLithophone is the "lithophone" value.
	PitchedValueLithophone PitchedValue = "lithophone"
	// PitchedValueMallet is the "mallet" value.
	PitchedValueMallet PitchedValue = "mallet"
	// PitchedValueMarimba is the "marimba" value.
	PitchedValueMarimba PitchedValue = "marimba"
	// PitchedValueSteelDrums is the "steel drums" value.
	PitchedValueSteelDrums PitchedValue = "steel drums"
	// PitchedValueTubaphone is the "tubaphone" value.
	PitchedValueTubaphone PitchedValue = "tubaphone"
	// PitchedValueTubularChimes is the "tubular chimes" value.
	PitchedValueTubularChimes PitchedValue = "tubular chimes"
	// PitchedValueVibraphone is the "vibraphone" value.
	PitchedValueVibraphone PitchedValue = "vibraphone"
	// PitchedValueXylophone is the "xylophone" value.
	PitchedValueXylophone PitchedValue = "xylophone"
)

// PositiveDecimal represents the "positive-decimal" XSD simple type.
type PositiveDecimal float64

// PositiveDivisions represents the "positive-divisions" XSD simple type.
type PositiveDivisions Divisions

// PositiveIntegerOrEmpty represents the "positive-integer-or-empty" XSD simple type.
type PositiveIntegerOrEmpty string

const (
	// PositiveIntegerOrEmptyEmpty is the empty value.
	PositiveIntegerOrEmptyEmpty PositiveIntegerOrEmpty = ""
)

// PrincipalVoiceSymbol represents the "principal-voice-symbol" XSD simple type.
type PrincipalVoiceSymbol string

const (
	// PrincipalVoiceSymbolHauptstimme is the "Hauptstimme" value.
	PrincipalVoiceSymbolHauptstimme PrincipalVoiceSymbol = "Hauptstimme"
	// PrincipalVoiceSymbolNebenstimme is the "Nebenstimme" value.
	PrincipalVoiceSymbolNebenstimme PrincipalVoiceSymbol = "Nebenstimme"
	// PrincipalVoiceSymbolPlain is the "plain" value.
	PrincipalVoiceSymbolPlain PrincipalVoiceSymbol = "plain"
	// PrincipalVoiceSymbolNone is the "none" value.
	PrincipalVoiceSymbolNone PrincipalVoiceSymbol = "none"
)

// RightLeftMiddle represents the "right-left-middle" XSD simple type.
type RightLeftMiddle string

const (
	// RightLeftMiddleRight is the "right" value.
	RightLeftMiddleRight RightLeftMiddle = "right"
	// RightLeftMiddleLeft is the "left" value.
	RightLeftMiddleLeft RightLeftMiddle = "left"
	// RightLeftMiddleMiddle is the "middle" value.
	RightLeftMiddleMiddle RightLeftMiddle = "middle"
)

// RotationDegrees represents the "rotation-degrees" XSD simple type.
type RotationDegrees float64

// SemiPitched represents the "semi-pitched" XSD simple type.
type SemiPitched string

const (
	// SemiPitchedHigh is the "high" value.
	SemiPitchedHigh SemiPitched = "high"
	// SemiPitchedMediumHigh is the "medium-high" value.
	SemiPitchedMediumHigh SemiPitched = "medium-high"
	// SemiPitchedMedium is the "medium" value.
	SemiPitchedMedium SemiPitched = "medium"
	// SemiPitchedMediumLow is the "medium-low" value.
	SemiPitchedMediumLow SemiPitched = "medium-low"
	// SemiPitchedLow is the "low" value.
	SemiPitchedLow SemiPitched = "low"
	// SemiPitchedVeryLow is the "very-low" value.
	SemiPitchedVeryLow SemiPitched = "very-low"
)

// Semitones represents the "semitones" XSD simple type.
type Semitones float64

// ShowFrets represents the "show-frets" XSD simple type.
type ShowFrets string

const (
	// ShowFretsNumbers is the "numbers" value.
	ShowFretsNumbers ShowFrets = "numbers"
	// ShowFretsLetters is the "letters" value.
	ShowFretsLetters ShowFrets = "letters"
)

// ShowTuplet represents the "show-tuplet" XSD simple type.
type ShowTuplet string

const (
	// ShowTupletActual is the "actual" value.
	ShowTupletActual ShowTuplet = "actual"
	// ShowTupletBoth is the "both" value.
	ShowTupletBoth ShowTuplet = "both"
	// ShowTupletNone is the "none" value.
	ShowTupletNone ShowTuplet = "none"
)

// SMuFLAccidentalGlyphName represents the "smufl-accidental-glyph-name" XSD simple type.
type SMuFLAccidentalGlyphName SMuFLGlyphName

// SMuFLCodaGlyphName represents the "smufl-coda-glyph-name" XSD simple type.
type SMuFLCodaGlyphName SMuFLGlyphName

// SMuFLGlyphName represents the "smufl-glyph-name" XSD simple type.
type SMuFLGlyphName string

// SMuFLLyricsGlyphName represents the "smufl-lyrics-glyph-name" XSD simple type.
type SMuFLLyricsGlyphName SMuFLGlyphName

// SMuFLPictogramGlyphName represents the "smufl-pictogram-glyph-name" XSD simple type.
type SMuFLPictogramGlyphName SMuFLGlyphName

// SMuFLSegnoGlyphName represents the "smufl-segno-glyph-name" XSD simple type.
type SMuFLSegnoGlyphName SMuFLGlyphName

// SMuFLWavyLineGlyphName represents the "smufl-wavy-line-glyph-name" XSD simple type.
type SMuFLWavyLineGlyphName SMuFLGlyphName

// StaffDivideSymbol represents the "staff-divide-symbol" XSD simple type.
type StaffDivideSymbol string

const (
	// StaffDivideSymbolDown is the "down" value.
	StaffDivideSymbolDown StaffDivideSymbol = "down"
	// StaffDivideSymbolUp is the "up" value.
	StaffDivideSymbolUp StaffDivideSymbol = "up"
	// StaffDivideSymbolUpDown is the "up-down" value.
	StaffDivideSymbolUpDown StaffDivideSymbol = "up-down"
)

// StaffLine represents the "staff-line" XSD simple type.
type StaffLine uint64

// StaffLinePosition represents the "staff-line-position" XSD simple type.
type StaffLinePosition int64

// StaffNumber represents the "staff-number" XSD simple type.
type StaffNumber uint64

// StaffType represents the "staff-type" XSD simple type.
type StaffType string

const (
	// StaffTypeOssia is the "ossia" value.
	StaffTypeOssia StaffType = "ossia"
	// StaffTypeEditorial is the "editorial" value.
	StaffTypeEditorial StaffType = "editorial"
	// StaffTypeCue is the "cue" value.
	StaffTypeCue StaffType = "cue"
	// StaffTypeAlternate is the "alternate" value.
	StaffTypeAlternate StaffType = "alternate"
	// StaffTypeRegular is the "regular" value.
	StaffTypeRegular StaffType = "regular"
)

// StartNote represents the "start-note" XSD simple type.
type StartNote string

const (
	// StartNoteUpper is the "upper" value.
	StartNoteUpper StartNote = "upper"
	// StartNoteMain is the "main" value.
	StartNoteMain StartNote = "main"
	// StartNoteBelow is the "below" value.
	StartNoteBelow StartNote = "below"
)

// StartStop represents the "start-stop" XSD simple type.
type StartStop string

const (
	// StartStopStart is the "start" value.
	StartStopStart StartStop = "start"
	// StartStopStop is the "stop" value.
	StartStopStop StartStop = "stop"
)

// StartStopChangeContinue represents the "start-stop-change-continue" XSD simple type.
type StartStopChangeContinue string

const (
	// StartStopChangeContinueStart is the "start" value.
	StartStopChangeContinueStart StartStopChangeContinue = "start"
	// StartStopChangeContinueStop is the "stop" value.
	StartStopChangeContinueStop StartStopChangeContinue = "stop"
	// StartStopChangeContinueChange is the "change" value.
	StartStopChangeContinueChange StartStopChangeContinue = "change"
	// StartStopChangeContinueContinue is the "continue" value.
	StartStopChangeContinueContinue StartStopChangeContinue = "continue"
)

// StartStopContinue represents the "start-stop-continue" XSD simple type.
type StartStopContinue string

const (
	// StartStopContinueStart is the "start" value.
	StartStopContinueStart StartStopContinue = "start"
	// StartStopContinueStop is the "stop" value.
	StartStopContinueStop StartStopContinue = "stop"
	// StartStopContinueContinue is the "continue" value.
	StartStopContinueContinue StartStopContinue = "continue"
)

// StartStopDiscontinue represents the "start-stop-discontinue" XSD simple type.
type StartStopDiscontinue string

const (
	// StartStopDiscontinueStart is the "start" value.
	StartStopDiscontinueStart StartStopDiscontinue = "start"
	// StartStopDiscontinueStop is the "stop" value.
	StartStopDiscontinueStop StartStopDiscontinue = "stop"
	// StartStopDiscontinueDiscontinue is the "discontinue" value.
	StartStopDiscontinueDiscontinue StartStopDiscontinue = "discontinue"
)

// StartStopSingle represents the "start-stop-single" XSD simple type.
type StartStopSingle string

const (
	// StartStopSingleStart is the "start" value.
	StartStopSingleStart StartStopSingle = "start"
	// StartStopSingleStop is the "stop" value.
	StartStopSingleStop StartStopSingle = "stop"
	// StartStopSingleSingle is the "single" value.
	StartStopSingleSingle StartStopSingle = "single"
)

// StemValue represents the "stem-value" XSD simple type.
type StemValue string

const (
	// StemValueDown is the "down" value.
	StemValueDown StemValue = "down"
	// StemValueUp is the "up" value.
	StemValueUp StemValue = "up"
	// StemValueDouble is the "double" value.
	StemValueDouble StemValue = "double"
	// StemValueNone is the "none" value.
	StemValueNone StemValue = "none"
)

// Step represents the "step" XSD simple type.
type Step string

const (
	// StepA is the "A" value.
	StepA Step = "A"
	// StepB is the "B" value.
	StepB Step = "B"
	// StepC is the "C" value.
	StepC Step = "C"
	// StepD is the "D" value.
	StepD Step = "D"
	// StepE is the "E" value.
	StepE Step = "E"
	// StepF is the "F" value.
	StepF Step = "F"
	// StepG is the "G" value.
	StepG Step = "G"
)

// StickLocation represents the "stick-location" XSD simple type.
type StickLocation string

const (
	// StickLocationCenter is the "center" value.
	StickLocationCenter StickLocation = "center"
	// StickLocationRim is the "rim" value.
	StickLocationRim StickLocation = "rim"
	// StickLocationCymbalBell is the "cymbal bell" value.
	StickLocationCymbalBell StickLocation = "cymbal bell"
	// StickLocationCymbalEdge is the "cymbal edge" value.
	StickLocationCymbalEdge StickLocation = "cymbal edge"
)

// StickMaterial represents the "stick-material" XSD simple type.
type StickMaterial string

const (
	// StickMaterialSoft is the "soft" value.
	StickMaterialSoft StickMaterial = "soft"
	// StickMaterialMedium is the "medium" value.
	StickMaterialMedium StickMaterial = "medium"
	// StickMaterialHard is the "hard" value.
	StickMaterialHard StickMaterial = "hard"
	// StickMaterialShaded is the "shaded" value.
	StickMaterialShaded StickMaterial = "shaded"
	// StickMaterialX is the "x" value.
	StickMaterialX StickMaterial = "x"
)

// StickType represents the "stick-type" XSD simple type.
type StickType string

const (
	// StickTypeBassDrum is the "bass drum" value.
	StickTypeBassDrum StickType = "bass drum"
	// StickTypeDoubleBassDrum is the "double bass drum" value.
	StickTypeDoubleBassDrum StickType = "double bass drum"
	// StickTypeGlockenspiel is the "glockenspiel" value.
	StickTypeGlockenspiel StickType = "glockenspiel"
	// StickTypeGum is the "gum" value.
	StickTypeGum StickType = "gum"
	// StickTypeHammer is the "hammer" value.
	StickTypeHammer StickType = "hammer"
	// StickTypeSuperball is the "superball" value.
	StickTypeSuperball StickType = "superball"
	// StickTypeTimpani is the "timpani" value.
	StickTypeTimpani StickType = "timpani"
	// StickTypeWound is the "wound" value.
	StickTypeWound StickType = "wound"
	// StickTypeXylophone is the "xylophone" value.
	StickTypeXylophone StickType = "xylophone"
	// StickTypeYarn is the "yarn" value.
	StickTypeYarn StickType = "yarn"
)

// StringNumber represents the "string-number" XSD simple type.
type StringNumber uint64

// SwingTypeValue represents the "swing-type-value" XSD simple type.
type SwingTypeValue NoteTypeValue

const (
	// SwingTypeValue16th is the "16th" value.
	SwingTypeValue16th SwingTypeValue = "16th"
	// SwingTypeValueEighth is the "eighth" value.
	SwingTypeValueEighth SwingTypeValue = "eighth"
)

// Syllabic represents the "syllabic" XSD simple type.
type Syllabic string

const (
	// SyllabicSingle is the "single" value.
	SyllabicSingle Syllabic = "single"
	// SyllabicBegin is the "begin" value.
	SyllabicBegin Syllabic = "begin"
	// SyllabicEnd is the "end" value.
	SyllabicEnd Syllabic = "end"
	// SyllabicMiddle is the "middle" value.
	SyllabicMiddle Syllabic = "middle"
)

// SymbolSize represents the "symbol-size" XSD simple type.
type SymbolSize string

const (
	// SymbolSizeFull is the "full" value.
	SymbolSizeFull SymbolSize = "full"
	// SymbolSizeCue is the "cue" value.
	SymbolSizeCue SymbolSize = "cue"
	// SymbolSizeGraceCue is the "grace-cue" value.
	SymbolSizeGraceCue SymbolSize = "grace-cue"
	// SymbolSizeLarge is the "large" value.
	SymbolSizeLarge SymbolSize = "large"
)

// SyncType represents the "sync-type" XSD simple type.
type SyncType string

const (
	// SyncTypeNone is the "none" value.
	SyncTypeNone SyncType = "none"
	// SyncTypeTempo is the "tempo" value.
	SyncTypeTempo SyncType = "tempo"
	// SyncTypeMostlyTempo is the "mostly-tempo" value.
	SyncTypeMostlyTempo SyncType = "mostly-tempo"
	// SyncTypeMostlyEvent is the "mostly-event" value.
	SyncTypeMostlyEvent SyncType = "mostly-event"
	// SyncTypeEvent is the "event" value.
	SyncTypeEvent SyncType = "event"
	// SyncTypeAlwaysEvent is the "always-event" value.
	SyncTypeAlwaysEvent SyncType = "always-event"
)

// SystemRelation represents the "system-relation" XSD simple type.
type SystemRelation SystemRelationNumber

const (
	// SystemRelationOnlyTop is the "only-top" value.
	SystemRelationOnlyTop SystemRelation = "only-top"
	// SystemRelationAlsoTop is the "also-top" value.
	SystemRelationAlsoTop SystemRelation = "also-top"
	// SystemRelationNone is the "none" value.
	SystemRelationNone SystemRelation = "none"
)

// SystemRelationNumber represents the "system-relation-number" XSD simple type.
type SystemRelationNumber string

const (
	// SystemRelationNumberOnlyTop is the "only-top" value.
	SystemRelationNumberOnlyTop SystemRelationNumber = "only-top"
	// SystemRelationNumberOnlyBottom is the "only-bottom" value.
	SystemRelationNumberOnlyBottom SystemRelationNumber = "only-bottom"
	// SystemRelationNumberAlsoTop is the "also-top" value.
	SystemRelationNumberAlsoTop SystemRelationNumber = "also-top"
	// SystemRelationNumberAlsoBottom is the "also-bottom" value.
	SystemRelationNumberAlsoBottom SystemRelationNumber = "also-bottom"
	// SystemRelationNumberNone is the "none" value.
	SystemRelationNumberNone SystemRelationNumber = "none"
)

// TapHand represents the "tap-hand" XSD simple type.
type TapHand string

const (
	// TapHandLeft is the "left" value.
	TapHandLeft TapHand = "left"
	// TapHandRight is the "right" value.
	TapHandRight TapHand = "right"
)

// Tenths represents the "tenths" XSD simple type.
type Tenths float64

// TextDirection represents the "text-direction" XSD simple type.
type TextDirection string

const (
	// TextDirectionLtr is the "ltr" value.
	TextDirectionLtr TextDirection = "ltr"
	// TextDirectionRtl is the "rtl" value.
	TextDirectionRtl TextDirection = "rtl"
	// TextDirectionLro is the "lro" value.
	TextDirectionLro TextDirection = "lro"
	// TextDirectionRlo is the "rlo" value.
	TextDirectionRlo TextDirection = "rlo"
)

// TiedType represents the "tied-type" XSD simple type.
type TiedType string

const (
	// TiedTypeStart is the "start" value.
	TiedTypeStart TiedType = "start"
	// TiedTypeStop is the "stop" value.
	TiedTypeStop TiedType = "stop"
	// TiedTypeContinue is the "continue" value.
	TiedTypeContinue TiedType = "continue"
	// TiedTypeLetRing is the "let-ring" value.
	TiedTypeLetRing TiedType = "let-ring"
)

// TimeOnly represents the "time-only" XSD simple type.
type TimeOnly string

// TimeRelation represents the "time-relation" XSD simple type.
type TimeRelation string

const (
	// TimeRelationParentheses is the "parentheses" value.
	TimeRelationParentheses TimeRelation = "parentheses"
	// TimeRelationBracket is the "bracket" value.
	TimeRelationBracket TimeRelation = "bracket"
	// TimeRelationEquals is the "equals" value.
	TimeRelationEquals TimeRelation = "equals"
	// TimeRelationSlash is the "slash" value.
	TimeRelationSlash TimeRelation = "slash"
	// TimeRelationSpace is the "space" value.
	TimeRelationSpace TimeRelation = "space"
	// TimeRelationHyphen is the "hyphen" value.
	TimeRelationHyphen TimeRelation = "hyphen"
)

// TimeSeparator represents the "time-separator" XSD simple type.
type TimeSeparator string

const (
	// TimeSeparatorNone is the "none" value.
	TimeSeparatorNone TimeSeparator = "none"
	// TimeSeparatorHorizontal is the "horizontal" value.
	TimeSeparatorHorizontal TimeSeparator = "horizontal"
	// TimeSeparatorDiagonal is the "diagonal" value.
	TimeSeparatorDiagonal TimeSeparator = "diagonal"
	// TimeSeparatorVertical is the "vertical" value.
	TimeSeparatorVertical TimeSeparator = "vertical"
	// TimeSeparatorAdjacent is the "adjacent" value.
	TimeSeparatorAdjacent TimeSeparator = "adjacent"
)

// TimeSymbol represents the "time-symbol" XSD simple type.
type TimeSymbol string

const (
	// TimeSymbolCommon is the "common" value.
	TimeSymbolCommon TimeSymbol = "common"
	// TimeSymbolCut is the "cut" value.
	TimeSymbolCut TimeSymbol = "cut"
	// TimeSymbolSingleNumber is the "single-number" value.
	TimeSymbolSingleNumber TimeSymbol = "single-number"
	// TimeSymbolNote is the "note" value.
	TimeSymbolNote TimeSymbol = "note"
	// TimeSymbolDottedNote is the "dotted-note" value.
	TimeSymbolDottedNote TimeSymbol = "dotted-note"
	// TimeSymbolNormal is the "normal" value.
	TimeSymbolNormal TimeSymbol = "normal"
)

// TipDirection represents the "tip-direction" XSD simple type.
type TipDirection string

const (
	// TipDirectionUp is the "up" value.
	TipDirectionUp TipDirection = "up"
	// TipDirectionDown is the "down" value.
	TipDirectionDown TipDirection = "down"
	// TipDirectionLeft is the "left" value.
	TipDirectionLeft TipDirection = "left"
	// TipDirectionRight is the "right" value.
	TipDirectionRight TipDirection = "right"
	// TipDirectionNorthwest is the "northwest" value.
	TipDirectionNorthwest TipDirection = "northwest"
	// TipDirectionNortheast is the "northeast" value.
	TipDirectionNortheast TipDirection = "northeast"
	// TipDirectionSoutheast is the "southeast" value.
	TipDirectionSoutheast TipDirection = "southeast"
	// TipDirectionSouthwest is the "southwest" value.
	TipDirectionSouthwest TipDirection = "southwest"
)

// TopBottom represents the "top-bottom" XSD simple type.
type TopBottom string

const (
	// TopBottomTop is the "top" value.
	TopBottomTop TopBottom = "top"
	// TopBottomBottom is the "bottom" value.
	TopBottomBottom TopBottom = "bottom"
)

// TremoloMarks represents the "tremolo-marks" XSD simple type.
type TremoloMarks int64

// TremoloType represents the "tremolo-type" XSD simple type.
type TremoloType string

const (
	// TremoloTypeStart is the "start" value.
	TremoloTypeStart TremoloType = "start"
	// TremoloTypeStop is the "stop" value.
	TremoloTypeStop TremoloType = "stop"
	// TremoloTypeSingle is the "single" value.
	TremoloTypeSingle TremoloType = "single"
	// TremoloTypeUnmeasured is the "unmeasured" value.
	TremoloTypeUnmeasured TremoloType = "unmeasured"
)

// TrillBeats represents the "trill-beats" XSD simple type.
type TrillBeats float64

// TrillStep represents the "trill-step" XSD simple type.
type TrillStep string

const (
	// TrillStepWhole is the "whole" value.
	TrillStepWhole TrillStep = "whole"
	// TrillStepHalf is the "half" value.
	TrillStepHalf TrillStep = "half"
	// TrillStepUnison is the "unison" value.
	TrillStepUnison TrillStep = "unison"
)

// TwoNoteTurn represents the "two-note-turn" XSD simple type.
type TwoNoteTurn string

const (
	// TwoNoteTurnWhole is the "whole" value.
	TwoNoteTurnWhole TwoNoteTurn = "whole"
	// TwoNoteTurnHalf is the "half" value.
	TwoNoteTurnHalf TwoNoteTurn = "half"
	// TwoNoteTurnNone is the "none" value.
	TwoNoteTurnNone TwoNoteTurn = "none"
)

// UpDown represents the "up-down" XSD simple type.
type UpDown string

const (
	// UpDownUp is the "up" value.
	UpDownUp UpDown = "up"
	// UpDownDown is the "down" value.
	UpDownDown UpDown = "down"
)

// UpDownStopContinue represents the "up-down-stop-continue" XSD simple type.
type UpDownStopContinue string

const (
	// UpDownStopContinueUp is the "up" value.
	UpDownStopContinueUp UpDownStopContinue = "up"
	// UpDownStopContinueDown is the "down" value.
	UpDownStopContinueDown UpDownStopContinue = "down"
	// UpDownStopContinueStop is the "stop" value.
	UpDownStopContinueStop UpDownStopContinue = "stop"
	// UpDownStopContinueContinue is the "continue" value.
	UpDownStopContinueContinue UpDownStopContinue = "continue"
)

// UprightInverted represents the "upright-inverted" XSD simple type.
type UprightInverted string

const (
	// UprightInvertedUpright is the "upright" value.
	UprightInvertedUpright UprightInverted = "upright"
	// UprightInvertedInverted is the "inverted" value.
	UprightInvertedInverted UprightInverted = "inverted"
)

// Valign represents the "valign" XSD simple type.
type Valign string

const (
	// ValignTop is the "top" value.
	ValignTop Valign = "top"
	// ValignMiddle is the "middle" value.
	ValignMiddle Valign = "middle"
	// ValignBottom is the "bottom" value.
	ValignBottom Valign = "bottom"
	// ValignBaseline is the "baseline" value.
	ValignBaseline Valign = "baseline"
)

// ValignImage represents the "valign-image" XSD simple type.
type ValignImage string

const (
	// ValignImageTop is the "top" value.
	ValignImageTop ValignImage = "top"
	// ValignImageMiddle is the "middle" value.
	ValignImageMiddle ValignImage = "middle"
	// ValignImageBottom is the "bottom" value.
	ValignImageBottom ValignImage = "bottom"
)

// WedgeType represents the "wedge-type" XSD simple type.
type WedgeType string

const (
	// WedgeTypeCrescendo is the "crescendo" value.
	WedgeTypeCrescendo WedgeType = "crescendo"
	// WedgeTypeDiminuendo is the "diminuendo" value.
	WedgeTypeDiminuendo WedgeType = "diminuendo"
	// WedgeTypeStop is the "stop" value.
	WedgeTypeStop WedgeType = "stop"
	// WedgeTypeContinue is the "continue" value.
	WedgeTypeContinue WedgeType = "continue"
)

// Winged represents the "winged" XSD simple type.
type Winged string

const (
	// WingedNone is the "none" value.
	WingedNone Winged = "none"
	// WingedStraight is the "straight" value.
	WingedStraight Winged = "straight"
	// WingedCurved is the "curved" value.
	WingedCurved Winged = "curved"
	// WingedDoubleStraight is the "double-straight" value.
	WingedDoubleStraight Winged = "double-straight"
	// WingedDoubleCurved is the "double-curved" value.
	WingedDoubleCurved Winged = "double-curved"
)

// WoodValue represents the "wood-value" XSD simple type.
type WoodValue string

const (
	// WoodValueBambooScraper is the "bamboo scraper" value.
	WoodValueBambooScraper WoodValue = "bamboo scraper"
	// WoodValueBoardClapper is the "board clapper" value.
	WoodValueBoardClapper WoodValue = "board clapper"
	// WoodValueCabasa is the "cabasa" value.
	WoodValueCabasa WoodValue = "cabasa"
	// WoodValueCastanets is the "castanets" value.
	WoodValueCastanets WoodValue = "castanets"
	// WoodValueCastanetsWithHandle is the "castanets with handle" value.
	WoodValueCastanetsWithHandle WoodValue = "castanets with handle"
	// WoodValueClaves is the "claves" value.
	WoodValueClaves WoodValue = "claves"
	// WoodValueFootballRattle is the "football rattle" value.
	WoodValueFootballRattle WoodValue = "football rattle"
	// WoodValueGuiro is the "guiro" value.
	WoodValueGuiro WoodValue = "guiro"
	// WoodValueLogDrum is the "log drum" value.
	WoodValueLogDrum WoodValue = "log drum"
	// WoodValueMaraca is the "maraca" value.
	WoodValueMaraca WoodValue = "maraca"
	// WoodValueMaracas is the "maracas" value.
	WoodValueMaracas WoodValue = "maracas"
	// WoodValueQuijada is the "quijada" value.
	WoodValueQuijada WoodValue = "quijada"
	// WoodValueRainstick is the "rainstick" value.
	WoodValueRainstick WoodValue = "rainstick"
	// WoodValueRatchet is the "ratchet" value.
	WoodValueRatchet WoodValue = "ratchet"
	// WoodValueRecoReco is the "reco-reco" value.
	WoodValueRecoReco WoodValue = "reco-reco"
	// WoodValueSandpaperBlocks is the "sandpaper blocks" value.
	WoodValueSandpaperBlocks WoodValue = "sandpaper blocks"
	// WoodValueSlitDrum is the "slit drum" value.
	WoodValueSlitDrum WoodValue = "slit drum"
	// WoodValueTempleBlock is the "temple block" value.
	WoodValueTempleBlock WoodValue = "temple block"
	// WoodValueVibraslap is the "vibraslap" value.
	WoodValueVibraslap WoodValue = "vibraslap"
	// WoodValueWhip is the "whip" value.
	WoodValueWhip WoodValue = "whip"
	// WoodValueWoodBlock is the "wood block" value.
	WoodValueWoodBlock WoodValue = "wood block"
)

// YesNo represents the "yes-no" XSD simple type.
type YesNo string

const (
	// YesNoYes is the "yes" value.
	YesNoYes YesNo = "yes"
	// YesNoNo is the "no" value.
	YesNoNo YesNo = "no"
)

// YesNoNumber represents the "yes-no-number" XSD simple type.
type YesNoNumber string

// YYYYMMDD represents the "yyyy-mm-dd" XSD simple type.
type YYYYMMDD string
