// Code generated by xsdgen; DO NOT EDIT.

package musicxml

import (
	"encoding/xml"
	"fmt"
)

// OpusLink represents the "opus-link" XSD complex type.
type OpusLink struct {
	Href    string  `xml:"http://www.w3.org/1999/xlink href,attr"`
	Type    *string `xml:"http://www.w3.org/1999/xlink type,attr,omitempty"`
	Role    *string `xml:"http://www.w3.org/1999/xlink role,attr,omitempty"`
	Title   *string `xml:"http://www.w3.org/1999/xlink title,attr,omitempty"`
	Show    *string `xml:"http://www.w3.org/1999/xlink show,attr,omitempty"`
	Actuate *string `xml:"http://www.w3.org/1999/xlink actuate,attr,omitempty"`
}

// EffectiveType returns Type when explicitly present and the XSD fixed value "simple" otherwise.
func (value *OpusLink) EffectiveType() string {
	if value != nil && value.Type != nil {
		return *value.Type
	}
	return "simple"
}

// TypeMatchesFixed reports whether Type is absent or equals its XSD fixed value "simple".
func (value *OpusLink) TypeMatchesFixed() bool {
	return value == nil || value.Type == nil || *value.Type == "simple"
}

// EffectiveShow returns Show when explicitly present and the XSD default value "replace" otherwise.
func (value *OpusLink) EffectiveShow() string {
	if value != nil && value.Show != nil {
		return *value.Show
	}
	return "replace"
}

// EffectiveActuate returns Actuate when explicitly present and the XSD default value "onRequest" otherwise.
func (value *OpusLink) EffectiveActuate() string {
	if value != nil && value.Actuate != nil {
		return *value.Actuate
	}
	return "onRequest"
}

// OpusScore represents the "score" XSD complex type.
type OpusScore struct {
	NewPage *YesNo  `xml:"new-page,attr,omitempty"`
	Href    string  `xml:"http://www.w3.org/1999/xlink href,attr"`
	Type    *string `xml:"http://www.w3.org/1999/xlink type,attr,omitempty"`
	Role    *string `xml:"http://www.w3.org/1999/xlink role,attr,omitempty"`
	Title   *string `xml:"http://www.w3.org/1999/xlink title,attr,omitempty"`
	Show    *string `xml:"http://www.w3.org/1999/xlink show,attr,omitempty"`
	Actuate *string `xml:"http://www.w3.org/1999/xlink actuate,attr,omitempty"`
}

// EffectiveType returns Type when explicitly present and the XSD fixed value "simple" otherwise.
func (value *OpusScore) EffectiveType() string {
	if value != nil && value.Type != nil {
		return *value.Type
	}
	return "simple"
}

// TypeMatchesFixed reports whether Type is absent or equals its XSD fixed value "simple".
func (value *OpusScore) TypeMatchesFixed() bool {
	return value == nil || value.Type == nil || *value.Type == "simple"
}

// EffectiveShow returns Show when explicitly present and the XSD default value "replace" otherwise.
func (value *OpusScore) EffectiveShow() string {
	if value != nil && value.Show != nil {
		return *value.Show
	}
	return "replace"
}

// EffectiveActuate returns Actuate when explicitly present and the XSD default value "onRequest" otherwise.
func (value *OpusScore) EffectiveActuate() string {
	if value != nil && value.Actuate != nil {
		return *value.Actuate
	}
	return "onRequest"
}

// OpusDocument represents the "opus" root element.
type OpusDocument struct {
	XMLName xml.Name              `xml:"opus"`
	Title   *string               `xml:"title,omitempty"`
	Content []OpusDocumentContent `xml:",any"`
	Version *string               `xml:"version,attr,omitempty"`
}

// EffectiveVersion returns Version when explicitly present and the XSD default value "1.0" otherwise.
func (value *OpusDocument) EffectiveVersion() string {
	if value != nil && value.Version != nil {
		return *value.Version
	}
	return "1.0"
}

// OpusDocumentContent is one ordered child element of OpusDocument.
type OpusDocumentContent struct {
	Opus     *OpusDocument
	OpusLink *OpusLink
	Score    *OpusScore
}

// AddOpus appends the "opus" child while preserving content order.
func (value *OpusDocument) AddOpus(element *OpusDocument) *OpusDocument {
	value.Content = append(value.Content, OpusDocumentContent{Opus: element})
	return element
}

// AddOpusLink appends the "opus-link" child while preserving content order.
func (value *OpusDocument) AddOpusLink(element *OpusLink) *OpusLink {
	value.Content = append(value.Content, OpusDocumentContent{OpusLink: element})
	return element
}

// AddScore appends the "score" child while preserving content order.
func (value *OpusDocument) AddScore(element *OpusScore) *OpusScore {
	value.Content = append(value.Content, OpusDocumentContent{Score: element})
	return element
}

// UnmarshalXML decodes one OpusDocumentContent variant.
func (value *OpusDocumentContent) UnmarshalXML(
	decoder *xml.Decoder,
	start xml.StartElement,
) error {
	*value = OpusDocumentContent{}

	switch start.Name {
	case (xml.Name{Local: "opus"}):
		var decoded OpusDocument
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode OpusDocumentContent.Opus: %w", err)
		}
		value.Opus = &decoded
		return nil

	case (xml.Name{Local: "opus-link"}):
		var decoded OpusLink
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode OpusDocumentContent.OpusLink: %w", err)
		}
		value.OpusLink = &decoded
		return nil

	case (xml.Name{Local: "score"}):
		var decoded OpusScore
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode OpusDocumentContent.Score: %w", err)
		}
		value.Score = &decoded
		return nil

	default:
		return fmt.Errorf(
			"musicxml: unsupported OpusDocumentContent element {%s}%s",
			start.Name.Space,
			start.Name.Local,
		)
	}
}

// MarshalXML encodes the selected OpusDocumentContent variant.
func (value OpusDocumentContent) MarshalXML(
	encoder *xml.Encoder,
	_ xml.StartElement,
) error {
	selected := 0
	if value.Opus != nil {
		selected++
	}
	if value.OpusLink != nil {
		selected++
	}
	if value.Score != nil {
		selected++
	}
	if selected != 1 {
		return fmt.Errorf("musicxml: OpusDocumentContent must contain exactly one value, got %d", selected)
	}

	switch {
	case value.Opus != nil:
		start := xml.StartElement{Name: xml.Name{Local: "opus"}}
		if err := encoder.EncodeElement(value.Opus, start); err != nil {
			return fmt.Errorf("musicxml: encode OpusDocumentContent.Opus: %w", err)
		}
		return nil
	case value.OpusLink != nil:
		start := xml.StartElement{Name: xml.Name{Local: "opus-link"}}
		if err := encoder.EncodeElement(value.OpusLink, start); err != nil {
			return fmt.Errorf("musicxml: encode OpusDocumentContent.OpusLink: %w", err)
		}
		return nil
	case value.Score != nil:
		start := xml.StartElement{Name: xml.Name{Local: "score"}}
		if err := encoder.EncodeElement(value.Score, start); err != nil {
			return fmt.Errorf("musicxml: encode OpusDocumentContent.Score: %w", err)
		}
		return nil
	}

	return nil
}
