// Code generated by xsdgen; DO NOT EDIT.

package musicxml

import (
	"encoding/xml"
	"fmt"
)

// ScorePartwise represents the "score-partwise" root element.
type ScorePartwise struct {
	XMLName        xml.Name            `xml:"score-partwise"`
	Work           *Work               `xml:"work,omitempty"`
	MovementNumber *string             `xml:"movement-number,omitempty"`
	MovementTitle  *string             `xml:"movement-title,omitempty"`
	Identification *Identification     `xml:"identification,omitempty"`
	Defaults       *Defaults           `xml:"defaults,omitempty"`
	Credit         []Credit            `xml:"credit"`
	PartList       PartList            `xml:"part-list"`
	Part           []ScorePartwisePart `xml:"part"`
	Version        *string             `xml:"version,attr,omitempty"`
}

// EffectiveVersion returns Version when explicitly present and the XSD default value "1.0" otherwise.
func (value *ScorePartwise) EffectiveVersion() string {
	if value != nil && value.Version != nil {
		return *value.Version
	}
	return "1.0"
}

// ScoreTimewise represents the "score-timewise" root element.
type ScoreTimewise struct {
	XMLName        xml.Name               `xml:"score-timewise"`
	Work           *Work                  `xml:"work,omitempty"`
	MovementNumber *string                `xml:"movement-number,omitempty"`
	MovementTitle  *string                `xml:"movement-title,omitempty"`
	Identification *Identification        `xml:"identification,omitempty"`
	Defaults       *Defaults              `xml:"defaults,omitempty"`
	Credit         []Credit               `xml:"credit"`
	PartList       PartList               `xml:"part-list"`
	Measure        []ScoreTimewiseMeasure `xml:"measure"`
	Version        *string                `xml:"version,attr,omitempty"`
}

// EffectiveVersion returns Version when explicitly present and the XSD default value "1.0" otherwise.
func (value *ScoreTimewise) EffectiveVersion() string {
	if value != nil && value.Version != nil {
		return *value.Version
	}
	return "1.0"
}

// ScorePartwisePart represents an anonymous nested XSD complex type.
type ScorePartwisePart struct {
	Measure []ScorePartwisePartMeasure `xml:"measure"`
	ID      string                     `xml:"id,attr"`
}

// ScorePartwisePartMeasure represents an anonymous nested XSD complex type.
type ScorePartwisePartMeasure struct {
	Content        []ScorePartwisePartMeasureContent `xml:",any"`
	Number         string                            `xml:"number,attr"`
	Text           *MeasureText                      `xml:"text,attr,omitempty"`
	Implicit       *YesNo                            `xml:"implicit,attr,omitempty"`
	NonControlling *YesNo                            `xml:"non-controlling,attr,omitempty"`
	Width          *Tenths                           `xml:"width,attr,omitempty"`
	ID             *string                           `xml:"id,attr,omitempty"`
}

// ScoreTimewiseMeasure represents an anonymous nested XSD complex type.
type ScoreTimewiseMeasure struct {
	Part           []ScoreTimewiseMeasurePart `xml:"part"`
	Number         string                     `xml:"number,attr"`
	Text           *MeasureText               `xml:"text,attr,omitempty"`
	Implicit       *YesNo                     `xml:"implicit,attr,omitempty"`
	NonControlling *YesNo                     `xml:"non-controlling,attr,omitempty"`
	Width          *Tenths                    `xml:"width,attr,omitempty"`
	ID             *string                    `xml:"id,attr,omitempty"`
}

// ScoreTimewiseMeasurePart represents an anonymous nested XSD complex type.
type ScoreTimewiseMeasurePart struct {
	Content []ScoreTimewiseMeasurePartContent `xml:",any"`
	ID      string                            `xml:"id,attr"`
}

// ScorePartwisePartMeasureContent is one ordered child element of ScorePartwisePartMeasure.
type ScorePartwisePartMeasureContent struct {
	Note        *Note
	Backup      *Backup
	Forward     *Forward
	Direction   *Direction
	Attributes  *Attributes
	Harmony     *Harmony
	FiguredBass *FiguredBass
	Print       *Print
	Sound       *Sound
	Listening   *Listening
	Barline     *Barline
	Grouping    *Grouping
	Link        *Link
	Bookmark    *Bookmark
}

// AddNote appends the "note" child while preserving content order.
func (value *ScorePartwisePartMeasure) AddNote(element *Note) *Note {
	value.Content = append(value.Content, ScorePartwisePartMeasureContent{Note: element})
	return element
}

// AddBackup appends the "backup" child while preserving content order.
func (value *ScorePartwisePartMeasure) AddBackup(element *Backup) *Backup {
	value.Content = append(value.Content, ScorePartwisePartMeasureContent{Backup: element})
	return element
}

// AddForward appends the "forward" child while preserving content order.
func (value *ScorePartwisePartMeasure) AddForward(element *Forward) *Forward {
	value.Content = append(value.Content, ScorePartwisePartMeasureContent{Forward: element})
	return element
}

// AddDirection appends the "direction" child while preserving content order.
func (value *ScorePartwisePartMeasure) AddDirection(element *Direction) *Direction {
	value.Content = append(value.Content, ScorePartwisePartMeasureContent{Direction: element})
	return element
}

// AddAttributes appends the "attributes" child while preserving content order.
func (value *ScorePartwisePartMeasure) AddAttributes(element *Attributes) *Attributes {
	value.Content = append(value.Content, ScorePartwisePartMeasureContent{Attributes: element})
	return element
}

// AddHarmony appends the "harmony" child while preserving content order.
func (value *ScorePartwisePartMeasure) AddHarmony(element *Harmony) *Harmony {
	value.Content = append(value.Content, ScorePartwisePartMeasureContent{Harmony: element})
	return element
}

// AddFiguredBass appends the "figured-bass" child while preserving content order.
func (value *ScorePartwisePartMeasure) AddFiguredBass(element *FiguredBass) *FiguredBass {
	value.Content = append(value.Content, ScorePartwisePartMeasureContent{FiguredBass: element})
	return element
}

// AddPrint appends the "print" child while preserving content order.
func (value *ScorePartwisePartMeasure) AddPrint(element *Print) *Print {
	value.Content = append(value.Content, ScorePartwisePartMeasureContent{Print: element})
	return element
}

// AddSound appends the "sound" child while preserving content order.
func (value *ScorePartwisePartMeasure) AddSound(element *Sound) *Sound {
	value.Content = append(value.Content, ScorePartwisePartMeasureContent{Sound: element})
	return element
}

// AddListening appends the "listening" child while preserving content order.
func (value *ScorePartwisePartMeasure) AddListening(element *Listening) *Listening {
	value.Content = append(value.Content, ScorePartwisePartMeasureContent{Listening: element})
	return element
}

// AddBarline appends the "barline" child while preserving content order.
func (value *ScorePartwisePartMeasure) AddBarline(element *Barline) *Barline {
	value.Content = append(value.Content, ScorePartwisePartMeasureContent{Barline: element})
	return element
}

// AddGrouping appends the "grouping" child while preserving content order.
func (value *ScorePartwisePartMeasure) AddGrouping(element *Grouping) *Grouping {
	value.Content = append(value.Content, ScorePartwisePartMeasureContent{Grouping: element})
	return element
}

// AddLink appends the "link" child while preserving content order.
func (value *ScorePartwisePartMeasure) AddLink(element *Link) *Link {
	value.Content = append(value.Content, ScorePartwisePartMeasureContent{Link: element})
	return element
}

// AddBookmark appends the "bookmark" child while preserving content order.
func (value *ScorePartwisePartMeasure) AddBookmark(element *Bookmark) *Bookmark {
	value.Content = append(value.Content, ScorePartwisePartMeasureContent{Bookmark: element})
	return element
}

// UnmarshalXML decodes one ScorePartwisePartMeasureContent variant.
func (value *ScorePartwisePartMeasureContent) UnmarshalXML(
	decoder *xml.Decoder,
	start xml.StartElement,
) error {
	*value = ScorePartwisePartMeasureContent{}

	switch start.Name {
	case (xml.Name{Local: "note"}):
		var decoded Note
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScorePartwisePartMeasureContent.Note: %w", err)
		}
		value.Note = &decoded
		return nil

	case (xml.Name{Local: "backup"}):
		var decoded Backup
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScorePartwisePartMeasureContent.Backup: %w", err)
		}
		value.Backup = &decoded
		return nil

	case (xml.Name{Local: "forward"}):
		var decoded Forward
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScorePartwisePartMeasureContent.Forward: %w", err)
		}
		value.Forward = &decoded
		return nil

	case (xml.Name{Local: "direction"}):
		var decoded Direction
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScorePartwisePartMeasureContent.Direction: %w", err)
		}
		value.Direction = &decoded
		return nil

	case (xml.Name{Local: "attributes"}):
		var decoded Attributes
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScorePartwisePartMeasureContent.Attributes: %w", err)
		}
		value.Attributes = &decoded
		return nil

	case (xml.Name{Local: "harmony"}):
		var decoded Harmony
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScorePartwisePartMeasureContent.Harmony: %w", err)
		}
		value.Harmony = &decoded
		return nil

	case (xml.Name{Local: "figured-bass"}):
		var decoded FiguredBass
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScorePartwisePartMeasureContent.FiguredBass: %w", err)
		}
		value.FiguredBass = &decoded
		return nil

	case (xml.Name{Local: "print"}):
		var decoded Print
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScorePartwisePartMeasureContent.Print: %w", err)
		}
		value.Print = &decoded
		return nil

	case (xml.Name{Local: "sound"}):
		var decoded Sound
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScorePartwisePartMeasureContent.Sound: %w", err)
		}
		value.Sound = &decoded
		return nil

	case (xml.Name{Local: "listening"}):
		var decoded Listening
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScorePartwisePartMeasureContent.Listening: %w", err)
		}
		value.Listening = &decoded
		return nil

	case (xml.Name{Local: "barline"}):
		var decoded Barline
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScorePartwisePartMeasureContent.Barline: %w", err)
		}
		value.Barline = &decoded
		return nil

	case (xml.Name{Local: "grouping"}):
		var decoded Grouping
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScorePartwisePartMeasureContent.Grouping: %w", err)
		}
		value.Grouping = &decoded
		return nil

	case (xml.Name{Local: "link"}):
		var decoded Link
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScorePartwisePartMeasureContent.Link: %w", err)
		}
		value.Link = &decoded
		return nil

	case (xml.Name{Local: "bookmark"}):
		var decoded Bookmark
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScorePartwisePartMeasureContent.Bookmark: %w", err)
		}
		value.Bookmark = &decoded
		return nil

	default:
		return fmt.Errorf(
			"musicxml: unsupported ScorePartwisePartMeasureContent element {%s}%s",
			start.Name.Space,
			start.Name.Local,
		)
	}
}

// MarshalXML encodes the selected ScorePartwisePartMeasureContent variant.
func (value ScorePartwisePartMeasureContent) MarshalXML(
	encoder *xml.Encoder,
	_ xml.StartElement,
) error {
	selected := 0
	if value.Note != nil {
		selected++
	}
	if value.Backup != nil {
		selected++
	}
	if value.Forward != nil {
		selected++
	}
	if value.Direction != nil {
		selected++
	}
	if value.Attributes != nil {
		selected++
	}
	if value.Harmony != nil {
		selected++
	}
	if value.FiguredBass != nil {
		selected++
	}
	if value.Print != nil {
		selected++
	}
	if value.Sound != nil {
		selected++
	}
	if value.Listening != nil {
		selected++
	}
	if value.Barline != nil {
		selected++
	}
	if value.Grouping != nil {
		selected++
	}
	if value.Link != nil {
		selected++
	}
	if value.Bookmark != nil {
		selected++
	}
	if selected != 1 {
		return fmt.Errorf("musicxml: ScorePartwisePartMeasureContent must contain exactly one value, got %d", selected)
	}

	switch {
	case value.Note != nil:
		start := xml.StartElement{Name: xml.Name{Local: "note"}}
		if err := encoder.EncodeElement(value.Note, start); err != nil {
			return fmt.Errorf("musicxml: encode ScorePartwisePartMeasureContent.Note: %w", err)
		}
		return nil
	case value.Backup != nil:
		start := xml.StartElement{Name: xml.Name{Local: "backup"}}
		if err := encoder.EncodeElement(value.Backup, start); err != nil {
			return fmt.Errorf("musicxml: encode ScorePartwisePartMeasureContent.Backup: %w", err)
		}
		return nil
	case value.Forward != nil:
		start := xml.StartElement{Name: xml.Name{Local: "forward"}}
		if err := encoder.EncodeElement(value.Forward, start); err != nil {
			return fmt.Errorf("musicxml: encode ScorePartwisePartMeasureContent.Forward: %w", err)
		}
		return nil
	case value.Direction != nil:
		start := xml.StartElement{Name: xml.Name{Local: "direction"}}
		if err := encoder.EncodeElement(value.Direction, start); err != nil {
			return fmt.Errorf("musicxml: encode ScorePartwisePartMeasureContent.Direction: %w", err)
		}
		return nil
	case value.Attributes != nil:
		start := xml.StartElement{Name: xml.Name{Local: "attributes"}}
		if err := encoder.EncodeElement(value.Attributes, start); err != nil {
			return fmt.Errorf("musicxml: encode ScorePartwisePartMeasureContent.Attributes: %w", err)
		}
		return nil
	case value.Harmony != nil:
		start := xml.StartElement{Name: xml.Name{Local: "harmony"}}
		if err := encoder.EncodeElement(value.Harmony, start); err != nil {
			return fmt.Errorf("musicxml: encode ScorePartwisePartMeasureContent.Harmony: %w", err)
		}
		return nil
	case value.FiguredBass != nil:
		start := xml.StartElement{Name: xml.Name{Local: "figured-bass"}}
		if err := encoder.EncodeElement(value.FiguredBass, start); err != nil {
			return fmt.Errorf("musicxml: encode ScorePartwisePartMeasureContent.FiguredBass: %w", err)
		}
		return nil
	case value.Print != nil:
		start := xml.StartElement{Name: xml.Name{Local: "print"}}
		if err := encoder.EncodeElement(value.Print, start); err != nil {
			return fmt.Errorf("musicxml: encode ScorePartwisePartMeasureContent.Print: %w", err)
		}
		return nil
	case value.Sound != nil:
		start := xml.StartElement{Name: xml.Name{Local: "sound"}}
		if err := encoder.EncodeElement(value.Sound, start); err != nil {
			return fmt.Errorf("musicxml: encode ScorePartwisePartMeasureContent.Sound: %w", err)
		}
		return nil
	case value.Listening != nil:
		start := xml.StartElement{Name: xml.Name{Local: "listening"}}
		if err := encoder.EncodeElement(value.Listening, start); err != nil {
			return fmt.Errorf("musicxml: encode ScorePartwisePartMeasureContent.Listening: %w", err)
		}
		return nil
	case value.Barline != nil:
		start := xml.StartElement{Name: xml.Name{Local: "barline"}}
		if err := encoder.EncodeElement(value.Barline, start); err != nil {
			return fmt.Errorf("musicxml: encode ScorePartwisePartMeasureContent.Barline: %w", err)
		}
		return nil
	case value.Grouping != nil:
		start := xml.StartElement{Name: xml.Name{Local: "grouping"}}
		if err := encoder.EncodeElement(value.Grouping, start); err != nil {
			return fmt.Errorf("musicxml: encode ScorePartwisePartMeasureContent.Grouping: %w", err)
		}
		return nil
	case value.Link != nil:
		start := xml.StartElement{Name: xml.Name{Local: "link"}}
		if err := encoder.EncodeElement(value.Link, start); err != nil {
			return fmt.Errorf("musicxml: encode ScorePartwisePartMeasureContent.Link: %w", err)
		}
		return nil
	case value.Bookmark != nil:
		start := xml.StartElement{Name: xml.Name{Local: "bookmark"}}
		if err := encoder.EncodeElement(value.Bookmark, start); err != nil {
			return fmt.Errorf("musicxml: encode ScorePartwisePartMeasureContent.Bookmark: %w", err)
		}
		return nil
	}

	return nil
}

// ScoreTimewiseMeasurePartContent is one ordered child element of ScoreTimewiseMeasurePart.
type ScoreTimewiseMeasurePartContent struct {
	Note        *Note
	Backup      *Backup
	Forward     *Forward
	Direction   *Direction
	Attributes  *Attributes
	Harmony     *Harmony
	FiguredBass *FiguredBass
	Print       *Print
	Sound       *Sound
	Listening   *Listening
	Barline     *Barline
	Grouping    *Grouping
	Link        *Link
	Bookmark    *Bookmark
}

// AddNote appends the "note" child while preserving content order.
func (value *ScoreTimewiseMeasurePart) AddNote(element *Note) *Note {
	value.Content = append(value.Content, ScoreTimewiseMeasurePartContent{Note: element})
	return element
}

// AddBackup appends the "backup" child while preserving content order.
func (value *ScoreTimewiseMeasurePart) AddBackup(element *Backup) *Backup {
	value.Content = append(value.Content, ScoreTimewiseMeasurePartContent{Backup: element})
	return element
}

// AddForward appends the "forward" child while preserving content order.
func (value *ScoreTimewiseMeasurePart) AddForward(element *Forward) *Forward {
	value.Content = append(value.Content, ScoreTimewiseMeasurePartContent{Forward: element})
	return element
}

// AddDirection appends the "direction" child while preserving content order.
func (value *ScoreTimewiseMeasurePart) AddDirection(element *Direction) *Direction {
	value.Content = append(value.Content, ScoreTimewiseMeasurePartContent{Direction: element})
	return element
}

// AddAttributes appends the "attributes" child while preserving content order.
func (value *ScoreTimewiseMeasurePart) AddAttributes(element *Attributes) *Attributes {
	value.Content = append(value.Content, ScoreTimewiseMeasurePartContent{Attributes: element})
	return element
}

// AddHarmony appends the "harmony" child while preserving content order.
func (value *ScoreTimewiseMeasurePart) AddHarmony(element *Harmony) *Harmony {
	value.Content = append(value.Content, ScoreTimewiseMeasurePartContent{Harmony: element})
	return element
}

// AddFiguredBass appends the "figured-bass" child while preserving content order.
func (value *ScoreTimewiseMeasurePart) AddFiguredBass(element *FiguredBass) *FiguredBass {
	value.Content = append(value.Content, ScoreTimewiseMeasurePartContent{FiguredBass: element})
	return element
}

// AddPrint appends the "print" child while preserving content order.
func (value *ScoreTimewiseMeasurePart) AddPrint(element *Print) *Print {
	value.Content = append(value.Content, ScoreTimewiseMeasurePartContent{Print: element})
	return element
}

// AddSound appends the "sound" child while preserving content order.
func (value *ScoreTimewiseMeasurePart) AddSound(element *Sound) *Sound {
	value.Content = append(value.Content, ScoreTimewiseMeasurePartContent{Sound: element})
	return element
}

// AddListening appends the "listening" child while preserving content order.
func (value *ScoreTimewiseMeasurePart) AddListening(element *Listening) *Listening {
	value.Content = append(value.Content, ScoreTimewiseMeasurePartContent{Listening: element})
	return element
}

// AddBarline appends the "barline" child while preserving content order.
func (value *ScoreTimewiseMeasurePart) AddBarline(element *Barline) *Barline {
	value.Content = append(value.Content, ScoreTimewiseMeasurePartContent{Barline: element})
	return element
}

// AddGrouping appends the "grouping" child while preserving content order.
func (value *ScoreTimewiseMeasurePart) AddGrouping(element *Grouping) *Grouping {
	value.Content = append(value.Content, ScoreTimewiseMeasurePartContent{Grouping: element})
	return element
}

// AddLink appends the "link" child while preserving content order.
func (value *ScoreTimewiseMeasurePart) AddLink(element *Link) *Link {
	value.Content = append(value.Content, ScoreTimewiseMeasurePartContent{Link: element})
	return element
}

// AddBookmark appends the "bookmark" child while preserving content order.
func (value *ScoreTimewiseMeasurePart) AddBookmark(element *Bookmark) *Bookmark {
	value.Content = append(value.Content, ScoreTimewiseMeasurePartContent{Bookmark: element})
	return element
}

// UnmarshalXML decodes one ScoreTimewiseMeasurePartContent variant.
func (value *ScoreTimewiseMeasurePartContent) UnmarshalXML(
	decoder *xml.Decoder,
	start xml.StartElement,
) error {
	*value = ScoreTimewiseMeasurePartContent{}

	switch start.Name {
	case (xml.Name{Local: "note"}):
		var decoded Note
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScoreTimewiseMeasurePartContent.Note: %w", err)
		}
		value.Note = &decoded
		return nil

	case (xml.Name{Local: "backup"}):
		var decoded Backup
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScoreTimewiseMeasurePartContent.Backup: %w", err)
		}
		value.Backup = &decoded
		return nil

	case (xml.Name{Local: "forward"}):
		var decoded Forward
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScoreTimewiseMeasurePartContent.Forward: %w", err)
		}
		value.Forward = &decoded
		return nil

	case (xml.Name{Local: "direction"}):
		var decoded Direction
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScoreTimewiseMeasurePartContent.Direction: %w", err)
		}
		value.Direction = &decoded
		return nil

	case (xml.Name{Local: "attributes"}):
		var decoded Attributes
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScoreTimewiseMeasurePartContent.Attributes: %w", err)
		}
		value.Attributes = &decoded
		return nil

	case (xml.Name{Local: "harmony"}):
		var decoded Harmony
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScoreTimewiseMeasurePartContent.Harmony: %w", err)
		}
		value.Harmony = &decoded
		return nil

	case (xml.Name{Local: "figured-bass"}):
		var decoded FiguredBass
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScoreTimewiseMeasurePartContent.FiguredBass: %w", err)
		}
		value.FiguredBass = &decoded
		return nil

	case (xml.Name{Local: "print"}):
		var decoded Print
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScoreTimewiseMeasurePartContent.Print: %w", err)
		}
		value.Print = &decoded
		return nil

	case (xml.Name{Local: "sound"}):
		var decoded Sound
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScoreTimewiseMeasurePartContent.Sound: %w", err)
		}
		value.Sound = &decoded
		return nil

	case (xml.Name{Local: "listening"}):
		var decoded Listening
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScoreTimewiseMeasurePartContent.Listening: %w", err)
		}
		value.Listening = &decoded
		return nil

	case (xml.Name{Local: "barline"}):
		var decoded Barline
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScoreTimewiseMeasurePartContent.Barline: %w", err)
		}
		value.Barline = &decoded
		return nil

	case (xml.Name{Local: "grouping"}):
		var decoded Grouping
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScoreTimewiseMeasurePartContent.Grouping: %w", err)
		}
		value.Grouping = &decoded
		return nil

	case (xml.Name{Local: "link"}):
		var decoded Link
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScoreTimewiseMeasurePartContent.Link: %w", err)
		}
		value.Link = &decoded
		return nil

	case (xml.Name{Local: "bookmark"}):
		var decoded Bookmark
		if err := decoder.DecodeElement(&decoded, &start); err != nil {
			return fmt.Errorf("musicxml: decode ScoreTimewiseMeasurePartContent.Bookmark: %w", err)
		}
		value.Bookmark = &decoded
		return nil

	default:
		return fmt.Errorf(
			"musicxml: unsupported ScoreTimewiseMeasurePartContent element {%s}%s",
			start.Name.Space,
			start.Name.Local,
		)
	}
}

// MarshalXML encodes the selected ScoreTimewiseMeasurePartContent variant.
func (value ScoreTimewiseMeasurePartContent) MarshalXML(
	encoder *xml.Encoder,
	_ xml.StartElement,
) error {
	selected := 0
	if value.Note != nil {
		selected++
	}
	if value.Backup != nil {
		selected++
	}
	if value.Forward != nil {
		selected++
	}
	if value.Direction != nil {
		selected++
	}
	if value.Attributes != nil {
		selected++
	}
	if value.Harmony != nil {
		selected++
	}
	if value.FiguredBass != nil {
		selected++
	}
	if value.Print != nil {
		selected++
	}
	if value.Sound != nil {
		selected++
	}
	if value.Listening != nil {
		selected++
	}
	if value.Barline != nil {
		selected++
	}
	if value.Grouping != nil {
		selected++
	}
	if value.Link != nil {
		selected++
	}
	if value.Bookmark != nil {
		selected++
	}
	if selected != 1 {
		return fmt.Errorf("musicxml: ScoreTimewiseMeasurePartContent must contain exactly one value, got %d", selected)
	}

	switch {
	case value.Note != nil:
		start := xml.StartElement{Name: xml.Name{Local: "note"}}
		if err := encoder.EncodeElement(value.Note, start); err != nil {
			return fmt.Errorf("musicxml: encode ScoreTimewiseMeasurePartContent.Note: %w", err)
		}
		return nil
	case value.Backup != nil:
		start := xml.StartElement{Name: xml.Name{Local: "backup"}}
		if err := encoder.EncodeElement(value.Backup, start); err != nil {
			return fmt.Errorf("musicxml: encode ScoreTimewiseMeasurePartContent.Backup: %w", err)
		}
		return nil
	case value.Forward != nil:
		start := xml.StartElement{Name: xml.Name{Local: "forward"}}
		if err := encoder.EncodeElement(value.Forward, start); err != nil {
			return fmt.Errorf("musicxml: encode ScoreTimewiseMeasurePartContent.Forward: %w", err)
		}
		return nil
	case value.Direction != nil:
		start := xml.StartElement{Name: xml.Name{Local: "direction"}}
		if err := encoder.EncodeElement(value.Direction, start); err != nil {
			return fmt.Errorf("musicxml: encode ScoreTimewiseMeasurePartContent.Direction: %w", err)
		}
		return nil
	case value.Attributes != nil:
		start := xml.StartElement{Name: xml.Name{Local: "attributes"}}
		if err := encoder.EncodeElement(value.Attributes, start); err != nil {
			return fmt.Errorf("musicxml: encode ScoreTimewiseMeasurePartContent.Attributes: %w", err)
		}
		return nil
	case value.Harmony != nil:
		start := xml.StartElement{Name: xml.Name{Local: "harmony"}}
		if err := encoder.EncodeElement(value.Harmony, start); err != nil {
			return fmt.Errorf("musicxml: encode ScoreTimewiseMeasurePartContent.Harmony: %w", err)
		}
		return nil
	case value.FiguredBass != nil:
		start := xml.StartElement{Name: xml.Name{Local: "figured-bass"}}
		if err := encoder.EncodeElement(value.FiguredBass, start); err != nil {
			return fmt.Errorf("musicxml: encode ScoreTimewiseMeasurePartContent.FiguredBass: %w", err)
		}
		return nil
	case value.Print != nil:
		start := xml.StartElement{Name: xml.Name{Local: "print"}}
		if err := encoder.EncodeElement(value.Print, start); err != nil {
			return fmt.Errorf("musicxml: encode ScoreTimewiseMeasurePartContent.Print: %w", err)
		}
		return nil
	case value.Sound != nil:
		start := xml.StartElement{Name: xml.Name{Local: "sound"}}
		if err := encoder.EncodeElement(value.Sound, start); err != nil {
			return fmt.Errorf("musicxml: encode ScoreTimewiseMeasurePartContent.Sound: %w", err)
		}
		return nil
	case value.Listening != nil:
		start := xml.StartElement{Name: xml.Name{Local: "listening"}}
		if err := encoder.EncodeElement(value.Listening, start); err != nil {
			return fmt.Errorf("musicxml: encode ScoreTimewiseMeasurePartContent.Listening: %w", err)
		}
		return nil
	case value.Barline != nil:
		start := xml.StartElement{Name: xml.Name{Local: "barline"}}
		if err := encoder.EncodeElement(value.Barline, start); err != nil {
			return fmt.Errorf("musicxml: encode ScoreTimewiseMeasurePartContent.Barline: %w", err)
		}
		return nil
	case value.Grouping != nil:
		start := xml.StartElement{Name: xml.Name{Local: "grouping"}}
		if err := encoder.EncodeElement(value.Grouping, start); err != nil {
			return fmt.Errorf("musicxml: encode ScoreTimewiseMeasurePartContent.Grouping: %w", err)
		}
		return nil
	case value.Link != nil:
		start := xml.StartElement{Name: xml.Name{Local: "link"}}
		if err := encoder.EncodeElement(value.Link, start); err != nil {
			return fmt.Errorf("musicxml: encode ScoreTimewiseMeasurePartContent.Link: %w", err)
		}
		return nil
	case value.Bookmark != nil:
		start := xml.StartElement{Name: xml.Name{Local: "bookmark"}}
		if err := encoder.EncodeElement(value.Bookmark, start); err != nil {
			return fmt.Errorf("musicxml: encode ScoreTimewiseMeasurePartContent.Bookmark: %w", err)
		}
		return nil
	}

	return nil
}
